package classes;
// Generated 25/07/2016 11:36:44 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Animal generated by hbm2java
 */
public class Animal  implements java.io.Serializable {


     private int rghv;
     private Usuario usuario;
     private String especie;
     private String nome;
     private String raca;
     private String pelagem;
     private int sexo;
     private int idade;
     private double peso;
     private Date data;
     private Set entradas = new HashSet(0);

    public Animal() {
    }

	
    public Animal(int rghv, Usuario usuario, String especie, String nome, String raca, String pelagem, int sexo, int idade, double peso) {
        this.rghv = rghv;
        this.usuario = usuario;
        this.especie = especie;
        this.nome = nome;
        this.raca = raca;
        this.pelagem = pelagem;
        this.sexo = sexo;
        this.idade = idade;
        this.peso = peso;
    }
    public Animal(int rghv, Usuario usuario, String especie, String nome, String raca, String pelagem, int sexo, int idade, double peso, Date data, Set entradas) {
       this.rghv = rghv;
       this.usuario = usuario;
       this.especie = especie;
       this.nome = nome;
       this.raca = raca;
       this.pelagem = pelagem;
       this.sexo = sexo;
       this.idade = idade;
       this.peso = peso;
       this.data = data;
       this.entradas = entradas;
    }
   
    public int getRghv() {
        return this.rghv;
    }
    
    public void setRghv(int rghv) {
        this.rghv = rghv;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getEspecie() {
        return this.especie;
    }
    
    public void setEspecie(String especie) {
        this.especie = especie;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getRaca() {
        return this.raca;
    }
    
    public void setRaca(String raca) {
        this.raca = raca;
    }
    public String getPelagem() {
        return this.pelagem;
    }
    
    public void setPelagem(String pelagem) {
        this.pelagem = pelagem;
    }
    public int getSexo() {
        return this.sexo;
    }
    
    public void setSexo(int sexo) {
        this.sexo = sexo;
    }
    public int getIdade() {
        return this.idade;
    }
    
    public void setIdade(int idade) {
        this.idade = idade;
    }
    public double getPeso() {
        return this.peso;
    }
    
    public void setPeso(double peso) {
        this.peso = peso;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Set getEntradas() {
        return this.entradas;
    }
    
    public void setEntradas(Set entradas) {
        this.entradas = entradas;
    }




}


