package classes;
// Generated 25/07/2016 11:36:44 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Custo generated by hbm2java
 */
public class Custo  implements java.io.Serializable {


     private CustoId id;
     private Entrada entrada;
     private Produto produto;
     private Date data;
     private Integer quant;

    public Custo() {
    }

	
    public Custo(CustoId id, Entrada entrada, Produto produto) {
        this.id = id;
        this.entrada = entrada;
        this.produto = produto;
    }
    public Custo(CustoId id, Entrada entrada, Produto produto, Date data, Integer quant) {
       this.id = id;
       this.entrada = entrada;
       this.produto = produto;
       this.data = data;
       this.quant = quant;
    }
   
    public CustoId getId() {
        return this.id;
    }
    
    public void setId(CustoId id) {
        this.id = id;
    }
    public Entrada getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(Entrada entrada) {
        this.entrada = entrada;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Integer getQuant() {
        return this.quant;
    }
    
    public void setQuant(Integer quant) {
        this.quant = quant;
    }




}


