package classes;
// Generated 25/07/2016 11:36:44 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ExameImg generated by hbm2java
 */
public class ExameImg  implements java.io.Serializable {


     private Integer id;
     private Entrada entrada;
     private String regiao;
     private int idRadiograf;
     private int quant;
     private String laudo;
     private int rghv;
     private int idOpera;
     private Date data;
     private Set sistemasImgs = new HashSet(0);

    public ExameImg() {
    }

	
    public ExameImg(Entrada entrada, String regiao, int idRadiograf, int quant, String laudo, int rghv, int idOpera) {
        this.entrada = entrada;
        this.regiao = regiao;
        this.idRadiograf = idRadiograf;
        this.quant = quant;
        this.laudo = laudo;
        this.rghv = rghv;
        this.idOpera = idOpera;
    }
    public ExameImg(Entrada entrada, String regiao, int idRadiograf, int quant, String laudo, int rghv, int idOpera, Date data, Set sistemasImgs) {
       this.entrada = entrada;
       this.regiao = regiao;
       this.idRadiograf = idRadiograf;
       this.quant = quant;
       this.laudo = laudo;
       this.rghv = rghv;
       this.idOpera = idOpera;
       this.data = data;
       this.sistemasImgs = sistemasImgs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Entrada getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(Entrada entrada) {
        this.entrada = entrada;
    }
    public String getRegiao() {
        return this.regiao;
    }
    
    public void setRegiao(String regiao) {
        this.regiao = regiao;
    }
    public int getIdRadiograf() {
        return this.idRadiograf;
    }
    
    public void setIdRadiograf(int idRadiograf) {
        this.idRadiograf = idRadiograf;
    }
    public int getQuant() {
        return this.quant;
    }
    
    public void setQuant(int quant) {
        this.quant = quant;
    }
    public String getLaudo() {
        return this.laudo;
    }
    
    public void setLaudo(String laudo) {
        this.laudo = laudo;
    }
    public int getRghv() {
        return this.rghv;
    }
    
    public void setRghv(int rghv) {
        this.rghv = rghv;
    }
    public int getIdOpera() {
        return this.idOpera;
    }
    
    public void setIdOpera(int idOpera) {
        this.idOpera = idOpera;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Set getSistemasImgs() {
        return this.sistemasImgs;
    }
    
    public void setSistemasImgs(Set sistemasImgs) {
        this.sistemasImgs = sistemasImgs;
    }




}


