package classes;
// Generated 25/07/2016 11:36:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Float preco;
     private Integer quant;

    public Produto() {
    }

    public Produto(String nome, Float preco, Integer quant) {
       this.nome = nome;
       this.preco = preco;
       this.quant = quant;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Float getPreco() {
        return this.preco;
    }
    
    public void setPreco(Float preco) {
        this.preco = preco;
    }
    public Integer getQuant() {
        return this.quant;
    }
    
    public void setQuant(Integer quant) {
        this.quant = quant;
    }
}


