package classes;
// Generated 25/07/2016 11:36:44 by Hibernate Tools 4.3.1



/**
 * SistemasImg generated by hbm2java
 */
public class SistemasImg  implements java.io.Serializable {


     private Integer id;
     private ExameImg exameImg;
     private String nome;
     private String descricao;

    public SistemasImg() {
    }

    public SistemasImg(ExameImg exameImg, String nome, String descricao) {
       this.exameImg = exameImg;
       this.nome = nome;
       this.descricao = descricao;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public ExameImg getExameImg() {
        return this.exameImg;
    }
    
    public void setExameImg(ExameImg exameImg) {
        this.exameImg = exameImg;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


