package com.lades.sihv.model;
// Generated 01/08/2018 11:44:13 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AnimalPhoto generated by hbm2java
 */
@Entity
@Table(name="animalPhoto"
    ,catalog="bd_sihv"
)
public class AnimalPhoto  implements java.io.Serializable {


     private Integer pkAnimalPhoto;

    public AnimalPhoto() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_animalPhoto", unique=true, nullable=false)
    public Integer getPkAnimalPhoto() {
        return this.pkAnimalPhoto;
    }
    
    public void setPkAnimalPhoto(Integer pkAnimalPhoto) {
        this.pkAnimalPhoto = pkAnimalPhoto;
    }




}


