package com.lades.sihv.model;
// Generated 04/10/2018 16:09:37 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Animals generated by hbm2java
 */
@Entity
@Table(name="animals"
    ,catalog="bd_sihv"
)
public class Animals  implements java.io.Serializable {


     private Integer pkAnimal;
     private String animalName;
     private String genderAnimal;
     private String animalAge;
     private boolean deathAnimal;
     private Date registrationDate;
     private Set ownersHasAnimalses = new HashSet(0);
     private Set animalPhotos = new HashSet(0);
     private Set smallAnimals = new HashSet(0);

    public Animals() {
    }

	
    public Animals(String animalName, String genderAnimal, String animalAge, boolean deathAnimal, Date registrationDate) {
        this.animalName = animalName;
        this.genderAnimal = genderAnimal;
        this.animalAge = animalAge;
        this.deathAnimal = deathAnimal;
        this.registrationDate = registrationDate;
    }
    public Animals(String animalName, String genderAnimal, String animalAge, boolean deathAnimal, Date registrationDate, Set ownersHasAnimalses, Set animalPhotos, Set smallAnimals) {
       this.animalName = animalName;
       this.genderAnimal = genderAnimal;
       this.animalAge = animalAge;
       this.deathAnimal = deathAnimal;
       this.registrationDate = registrationDate;
       this.ownersHasAnimalses = ownersHasAnimalses;
       this.animalPhotos = animalPhotos;
       this.smallAnimals = smallAnimals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_animal", unique=true, nullable=false)
    public Integer getPkAnimal() {
        return this.pkAnimal;
    }
    
    public void setPkAnimal(Integer pkAnimal) {
        this.pkAnimal = pkAnimal;
    }

    
    @Column(name="animalName", nullable=false, length=70)
    public String getAnimalName() {
        return this.animalName;
    }
    
    public void setAnimalName(String animalName) {
        this.animalName = animalName;
    }

    
    @Column(name="genderAnimal", nullable=false, length=3)
    public String getGenderAnimal() {
        return this.genderAnimal;
    }
    
    public void setGenderAnimal(String genderAnimal) {
        this.genderAnimal = genderAnimal;
    }

    
    @Column(name="animalAge", nullable=false, length=100)
    public String getAnimalAge() {
        return this.animalAge;
    }
    
    public void setAnimalAge(String animalAge) {
        this.animalAge = animalAge;
    }

    
    @Column(name="deathAnimal", nullable=false)
    public boolean isDeathAnimal() {
        return this.deathAnimal;
    }
    
    public void setDeathAnimal(boolean deathAnimal) {
        this.deathAnimal = deathAnimal;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="registrationDate", nullable=false, length=19)
    public Date getRegistrationDate() {
        return this.registrationDate;
    }
    
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="animals")
    public Set getOwnersHasAnimalses() {
        return this.ownersHasAnimalses;
    }
    
    public void setOwnersHasAnimalses(Set ownersHasAnimalses) {
        this.ownersHasAnimalses = ownersHasAnimalses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="animals")
    public Set getAnimalPhotos() {
        return this.animalPhotos;
    }
    
    public void setAnimalPhotos(Set animalPhotos) {
        this.animalPhotos = animalPhotos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="animals")
    public Set getSmallAnimals() {
        return this.smallAnimals;
    }
    
    public void setSmallAnimals(Set smallAnimals) {
        this.smallAnimals = smallAnimals;
    }




}


