package com.lades.sihv.model;
// Generated 02/11/2018 14:22:32 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
    ,catalog="bd_sihv"
)
public class Category  implements java.io.Serializable {


     private Integer pkCategory;
     private String abbreviation;
     private String description;
     private boolean logicalExclusion;
     private Date dateOfLastModification;
     private Date dateOfFirstRegistration;
     private Set priceses = new HashSet(0);

    public Category() {
    }

	
    public Category(String abbreviation, String description, boolean logicalExclusion, Date dateOfLastModification, Date dateOfFirstRegistration) {
        this.abbreviation = abbreviation;
        this.description = description;
        this.logicalExclusion = logicalExclusion;
        this.dateOfLastModification = dateOfLastModification;
        this.dateOfFirstRegistration = dateOfFirstRegistration;
    }
    public Category(String abbreviation, String description, boolean logicalExclusion, Date dateOfLastModification, Date dateOfFirstRegistration, Set priceses) {
       this.abbreviation = abbreviation;
       this.description = description;
       this.logicalExclusion = logicalExclusion;
       this.dateOfLastModification = dateOfLastModification;
       this.dateOfFirstRegistration = dateOfFirstRegistration;
       this.priceses = priceses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_category", unique=true, nullable=false)
    public Integer getPkCategory() {
        return this.pkCategory;
    }
    
    public void setPkCategory(Integer pkCategory) {
        this.pkCategory = pkCategory;
    }

    
    @Column(name="abbreviation", nullable=false, length=2)
    public String getAbbreviation() {
        return this.abbreviation;
    }
    
    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation;
    }

    
    @Column(name="description", nullable=false, length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="logicalExclusion", nullable=false)
    public boolean isLogicalExclusion() {
        return this.logicalExclusion;
    }
    
    public void setLogicalExclusion(boolean logicalExclusion) {
        this.logicalExclusion = logicalExclusion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateOfLastModification", nullable=false, length=10)
    public Date getDateOfLastModification() {
        return this.dateOfLastModification;
    }
    
    public void setDateOfLastModification(Date dateOfLastModification) {
        this.dateOfLastModification = dateOfLastModification;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateOfFirstRegistration", nullable=false, length=19)
    public Date getDateOfFirstRegistration() {
        return this.dateOfFirstRegistration;
    }
    
    public void setDateOfFirstRegistration(Date dateOfFirstRegistration) {
        this.dateOfFirstRegistration = dateOfFirstRegistration;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    public Set getPriceses() {
        return this.priceses;
    }
    
    public void setPriceses(Set priceses) {
        this.priceses = priceses;
    }




}


