package com.lades.sihv.model;
// Generated 25/09/2018 14:47:05 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name="city"
    ,catalog="bd_sihv"
)
public class City  implements java.io.Serializable {


     private Integer pkCity;
     private FederationUnity federationUnity;
     private String fullNameCity;
     private Date registrationDate;
     private Set neighborhoods = new HashSet(0);

    public City() {
    }

	
    public City(FederationUnity federationUnity, String fullNameCity, Date registrationDate) {
        this.federationUnity = federationUnity;
        this.fullNameCity = fullNameCity;
        this.registrationDate = registrationDate;
    }
    public City(FederationUnity federationUnity, String fullNameCity, Date registrationDate, Set neighborhoods) {
       this.federationUnity = federationUnity;
       this.fullNameCity = fullNameCity;
       this.registrationDate = registrationDate;
       this.neighborhoods = neighborhoods;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_city", unique=true, nullable=false)
    public Integer getPkCity() {
        return this.pkCity;
    }
    
    public void setPkCity(Integer pkCity) {
        this.pkCity = pkCity;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="federationUnity_PK_federationUnity", nullable=false)
    public FederationUnity getFederationUnity() {
        return this.federationUnity;
    }
    
    public void setFederationUnity(FederationUnity federationUnity) {
        this.federationUnity = federationUnity;
    }

    
    @Column(name="fullNameCity", nullable=false, length=100)
    public String getFullNameCity() {
        return this.fullNameCity;
    }
    
    public void setFullNameCity(String fullNameCity) {
        this.fullNameCity = fullNameCity;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="registrationDate", nullable=false, length=19)
    public Date getRegistrationDate() {
        return this.registrationDate;
    }
    
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="city")
    public Set getNeighborhoods() {
        return this.neighborhoods;
    }
    
    public void setNeighborhoods(Set neighborhoods) {
        this.neighborhoods = neighborhoods;
    }




}


