package com.lades.sihv.model;
// Generated 04/10/2018 16:09:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClassAnimal generated by hbm2java
 */
@Entity
@Table(name="classAnimal"
    ,catalog="bd_sihv"
)
public class ClassAnimal  implements java.io.Serializable {


     private Integer pkClassAnimal;
     private String nameClass;
     private Set orders = new HashSet(0);

    public ClassAnimal() {
    }

	
    public ClassAnimal(String nameClass) {
        this.nameClass = nameClass;
    }
    public ClassAnimal(String nameClass, Set orders) {
       this.nameClass = nameClass;
       this.orders = orders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_classAnimal", unique=true, nullable=false)
    public Integer getPkClassAnimal() {
        return this.pkClassAnimal;
    }
    
    public void setPkClassAnimal(Integer pkClassAnimal) {
        this.pkClassAnimal = pkClassAnimal;
    }

    
    @Column(name="nameClass", nullable=false, length=100)
    public String getNameClass() {
        return this.nameClass;
    }
    
    public void setNameClass(String nameClass) {
        this.nameClass = nameClass;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="classAnimal")
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }




}


