package com.lades.sihv.model;
// Generated 28/10/2016 09:58:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClienteId generated by hbm2java
 */
@Embeddable
public class ClienteId  implements java.io.Serializable {


     private int pkCliente;
     private int fkPessoa;

    public ClienteId() {
    }

    public ClienteId(int pkCliente, int fkPessoa) {
       this.pkCliente = pkCliente;
       this.fkPessoa = fkPessoa;
    }
   


    @Column(name="PK_cliente", nullable=false)
    public int getPkCliente() {
        return this.pkCliente;
    }
    
    public void setPkCliente(int pkCliente) {
        this.pkCliente = pkCliente;
    }


    @Column(name="FK_pessoa", nullable=false)
    public int getFkPessoa() {
        return this.fkPessoa;
    }
    
    public void setFkPessoa(int fkPessoa) {
        this.fkPessoa = fkPessoa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClienteId) ) return false;
		 ClienteId castOther = ( ClienteId ) other; 
         
		 return (this.getPkCliente()==castOther.getPkCliente())
 && (this.getFkPessoa()==castOther.getFkPessoa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkCliente();
         result = 37 * result + this.getFkPessoa();
         return result;
   }   


}


