package com.lades.sihv.model;
// Generated 08/11/2016 12:03:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="bd_sihv"
)
public class Cliente  implements java.io.Serializable {


     private ClienteId id;
     private Pessoa pessoa;
     private Set<Animais> animaises = new HashSet<Animais>(0);

    public Cliente() {
    }

	
    public Cliente(ClienteId id, Pessoa pessoa) {
        this.id = id;
        this.pessoa = pessoa;
    }
    public Cliente(ClienteId id, Pessoa pessoa, Set<Animais> animaises) {
       this.id = id;
       this.pessoa = pessoa;
       this.animaises = animaises;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pkCliente", column=@Column(name="PK_cliente", nullable=false) ), 
        @AttributeOverride(name="fkPessoa", column=@Column(name="FK_pessoa", nullable=false) ) } )
    public ClienteId getId() {
        return this.id;
    }
    
    public void setId(ClienteId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FK_pessoa", nullable=false, insertable=false, updatable=false)
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set<Animais> getAnimaises() {
        return this.animaises;
    }
    
    public void setAnimaises(Set<Animais> animaises) {
        this.animaises = animaises;
    }




}


