package com.lades.sihv.model;
// Generated 05/04/2018 16:39:59 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Consulta generated by hbm2java
 */
@Entity
@Table(name="consulta"
    ,catalog="bd_sihv"
)
public class Consulta  implements java.io.Serializable {


     private Integer pkConsulta;
     private Animais animais;
     private User user;
     private Date dataConsulta;
     private String sistemasAfetados;
     private String laudo;
     private String laudoConfirme;
     private BigDecimal valorConsulta;
     private Set sisDigestorios = new HashSet(0);
     private Set sisUrinarioMamarias = new HashSet(0);
     private Set exameImages = new HashSet(0);
     private Set sisMuscEsques = new HashSet(0);
     private Set exameFisicos = new HashSet(0);
     private Set sisRespCardios = new HashSet(0);
     private Set sisTegumentars = new HashSet(0);
     private Set anamneses = new HashSet(0);
     private Set sisOftalmicos = new HashSet(0);
     private Set sisNeurologicos = new HashSet(0);

    public Consulta() {
    }

	
    public Consulta(Animais animais, User user, Date dataConsulta, BigDecimal valorConsulta) {
        this.animais = animais;
        this.user = user;
        this.dataConsulta = dataConsulta;
        this.valorConsulta = valorConsulta;
    }
    public Consulta(Animais animais, User user, Date dataConsulta, String sistemasAfetados, String laudo, String laudoConfirme, BigDecimal valorConsulta, Set sisDigestorios, Set sisUrinarioMamarias, Set exameImages, Set sisMuscEsques, Set exameFisicos, Set sisRespCardios, Set sisTegumentars, Set anamneses, Set sisOftalmicos, Set sisNeurologicos) {
       this.animais = animais;
       this.user = user;
       this.dataConsulta = dataConsulta;
       this.sistemasAfetados = sistemasAfetados;
       this.laudo = laudo;
       this.laudoConfirme = laudoConfirme;
       this.valorConsulta = valorConsulta;
       this.sisDigestorios = sisDigestorios;
       this.sisUrinarioMamarias = sisUrinarioMamarias;
       this.exameImages = exameImages;
       this.sisMuscEsques = sisMuscEsques;
       this.exameFisicos = exameFisicos;
       this.sisRespCardios = sisRespCardios;
       this.sisTegumentars = sisTegumentars;
       this.anamneses = anamneses;
       this.sisOftalmicos = sisOftalmicos;
       this.sisNeurologicos = sisNeurologicos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_consulta", unique=true, nullable=false)
    public Integer getPkConsulta() {
        return this.pkConsulta;
    }
    
    public void setPkConsulta(Integer pkConsulta) {
        this.pkConsulta = pkConsulta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="animais_FK_animal", referencedColumnName="PK_animal", nullable=false), 
        @JoinColumn(name="animais_cliente_FK_cliente", referencedColumnName="cliente_FK_cliente", nullable=false), 
        @JoinColumn(name="animais_cliente_FK_pessoa", referencedColumnName="cliente_FK_pessoa", nullable=false) } )
    public Animais getAnimais() {
        return this.animais;
    }
    
    public void setAnimais(Animais animais) {
        this.animais = animais;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="user_PK_user", referencedColumnName="PK_user", nullable=false), 
        @JoinColumn(name="user_FK_pessoa", referencedColumnName="FK_pessoa", nullable=false) } )
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataConsulta", nullable=false, length=19)
    public Date getDataConsulta() {
        return this.dataConsulta;
    }
    
    public void setDataConsulta(Date dataConsulta) {
        this.dataConsulta = dataConsulta;
    }

    
    @Column(name="sistemasAfetados", length=500)
    public String getSistemasAfetados() {
        return this.sistemasAfetados;
    }
    
    public void setSistemasAfetados(String sistemasAfetados) {
        this.sistemasAfetados = sistemasAfetados;
    }

    
    @Column(name="laudo", length=500)
    public String getLaudo() {
        return this.laudo;
    }
    
    public void setLaudo(String laudo) {
        this.laudo = laudo;
    }

    
    @Column(name="laudoConfirme", length=7)
    public String getLaudoConfirme() {
        return this.laudoConfirme;
    }
    
    public void setLaudoConfirme(String laudoConfirme) {
        this.laudoConfirme = laudoConfirme;
    }

    
    @Column(name="valorConsulta", nullable=false, precision=6)
    public BigDecimal getValorConsulta() {
        return this.valorConsulta;
    }
    
    public void setValorConsulta(BigDecimal valorConsulta) {
        this.valorConsulta = valorConsulta;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="consulta")
    public Set getSisDigestorios() {
        return this.sisDigestorios;
    }
    
    public void setSisDigestorios(Set sisDigestorios) {
        this.sisDigestorios = sisDigestorios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="consulta")
    public Set getSisUrinarioMamarias() {
        return this.sisUrinarioMamarias;
    }
    
    public void setSisUrinarioMamarias(Set sisUrinarioMamarias) {
        this.sisUrinarioMamarias = sisUrinarioMamarias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="consulta")
    public Set getExameImages() {
        return this.exameImages;
    }
    
    public void setExameImages(Set exameImages) {
        this.exameImages = exameImages;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="consulta")
    public Set getSisMuscEsques() {
        return this.sisMuscEsques;
    }
    
    public void setSisMuscEsques(Set sisMuscEsques) {
        this.sisMuscEsques = sisMuscEsques;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="consulta")
    public Set getExameFisicos() {
        return this.exameFisicos;
    }
    
    public void setExameFisicos(Set exameFisicos) {
        this.exameFisicos = exameFisicos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="consulta")
    public Set getSisRespCardios() {
        return this.sisRespCardios;
    }
    
    public void setSisRespCardios(Set sisRespCardios) {
        this.sisRespCardios = sisRespCardios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="consulta")
    public Set getSisTegumentars() {
        return this.sisTegumentars;
    }
    
    public void setSisTegumentars(Set sisTegumentars) {
        this.sisTegumentars = sisTegumentars;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="consulta")
    public Set getAnamneses() {
        return this.anamneses;
    }
    
    public void setAnamneses(Set anamneses) {
        this.anamneses = anamneses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="consulta")
    public Set getSisOftalmicos() {
        return this.sisOftalmicos;
    }
    
    public void setSisOftalmicos(Set sisOftalmicos) {
        this.sisOftalmicos = sisOftalmicos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="consulta")
    public Set getSisNeurologicos() {
        return this.sisNeurologicos;
    }
    
    public void setSisNeurologicos(Set sisNeurologicos) {
        this.sisNeurologicos = sisNeurologicos;
    }




}


