package com.lades.sihv.model;
// Generated 04/10/2018 16:09:37 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cpf generated by hbm2java
 */
@Entity
@Table(name="cpf"
    ,catalog="bd_sihv"
    , uniqueConstraints = @UniqueConstraint(columnNames="cpf") 
)
public class Cpf  implements java.io.Serializable {


     private Integer pkCpf;
     private PhysicalPerson physicalPerson;
     private String cpf;

    public Cpf() {
    }

    public Cpf(PhysicalPerson physicalPerson, String cpf) {
       this.physicalPerson = physicalPerson;
       this.cpf = cpf;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_cpf", unique=true, nullable=false)
    public Integer getPkCpf() {
        return this.pkCpf;
    }
    
    public void setPkCpf(Integer pkCpf) {
        this.pkCpf = pkCpf;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="physicalPerson_PK_physicalPerson", referencedColumnName="PK_physicalPerson", nullable=false), 
        @JoinColumn(name="physicalPerson_people_PK_person", referencedColumnName="people_PK_person", nullable=false) } )
    public PhysicalPerson getPhysicalPerson() {
        return this.physicalPerson;
    }
    
    public void setPhysicalPerson(PhysicalPerson physicalPerson) {
        this.physicalPerson = physicalPerson;
    }

    
    @Column(name="cpf", unique=true, nullable=false, length=18)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }




}


