package com.lades.sihv.model;
// Generated 25/09/2018 14:47:05 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cpf generated by hbm2java
 */
@Entity
@Table(name="cpf"
    ,catalog="bd_sihv"
    , uniqueConstraints = @UniqueConstraint(columnNames="cpf") 
)
public class Cpf  implements java.io.Serializable {


     private CpfId id;
     private PhysicalPerson physicalPerson;
     private String cpf;

    public Cpf() {
    }

    public Cpf(CpfId id, PhysicalPerson physicalPerson, String cpf) {
       this.id = id;
       this.physicalPerson = physicalPerson;
       this.cpf = cpf;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pkCpf", column=@Column(name="PK_cpf", nullable=false) ), 
        @AttributeOverride(name="physicalPersonPkPhysicalPerson", column=@Column(name="physicalPerson_PK_physicalPerson", nullable=false) ), 
        @AttributeOverride(name="physicalPersonPeoplePkPerson", column=@Column(name="physicalPerson_people_PK_person", nullable=false) ) } )
    public CpfId getId() {
        return this.id;
    }
    
    public void setId(CpfId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="physicalPerson_PK_physicalPerson", referencedColumnName="PK_physicalPerson", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="physicalPerson_people_PK_person", referencedColumnName="people_PK_person", nullable=false, insertable=false, updatable=false) } )
    public PhysicalPerson getPhysicalPerson() {
        return this.physicalPerson;
    }
    
    public void setPhysicalPerson(PhysicalPerson physicalPerson) {
        this.physicalPerson = physicalPerson;
    }

    
    @Column(name="cpf", unique=true, nullable=false, length=18)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }




}


