package com.lades.sihv.model;
// Generated 09/01/2017 01:03:35 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExameImage generated by hbm2java
 */
@Entity
@Table(name="exameImage"
    ,catalog="bd_sihv"
)
public class ExameImage  implements java.io.Serializable {


     private ExameImageId id;
     private Consulta consulta;
     private String regiExami;
     private String posicao;
     private Integer qtdChapas;
     private String laudo;
     private String tipo;
     private Date dataExaImage;
     private String status;
     private String codExameImage;

    public ExameImage() {
    }

	
    public ExameImage(ExameImageId id, Consulta consulta, String regiExami, String tipo, Date dataExaImage, String status, String codExameImage) {
        this.id = id;
        this.consulta = consulta;
        this.regiExami = regiExami;
        this.tipo = tipo;
        this.dataExaImage = dataExaImage;
        this.status = status;
        this.codExameImage = codExameImage;
    }
    public ExameImage(ExameImageId id, Consulta consulta, String regiExami, String posicao, Integer qtdChapas, String laudo, String tipo, Date dataExaImage, String status, String codExameImage) {
       this.id = id;
       this.consulta = consulta;
       this.regiExami = regiExami;
       this.posicao = posicao;
       this.qtdChapas = qtdChapas;
       this.laudo = laudo;
       this.tipo = tipo;
       this.dataExaImage = dataExaImage;
       this.status = status;
       this.codExameImage = codExameImage;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pkExameImage", column=@Column(name="PK_exameImage", nullable=false) ), 
        @AttributeOverride(name="consultaFkConsulta", column=@Column(name="consulta_FK_consulta", nullable=false) ) } )
    public ExameImageId getId() {
        return this.id;
    }
    
    public void setId(ExameImageId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="consulta_FK_consulta", nullable=false, insertable=false, updatable=false)
    public Consulta getConsulta() {
        return this.consulta;
    }
    
    public void setConsulta(Consulta consulta) {
        this.consulta = consulta;
    }

    
    @Column(name="regiExami", nullable=false, length=200)
    public String getRegiExami() {
        return this.regiExami;
    }
    
    public void setRegiExami(String regiExami) {
        this.regiExami = regiExami;
    }

    
    @Column(name="posicao", length=50)
    public String getPosicao() {
        return this.posicao;
    }
    
    public void setPosicao(String posicao) {
        this.posicao = posicao;
    }

    
    @Column(name="qtdChapas")
    public Integer getQtdChapas() {
        return this.qtdChapas;
    }
    
    public void setQtdChapas(Integer qtdChapas) {
        this.qtdChapas = qtdChapas;
    }

    
    @Column(name="laudo", length=200)
    public String getLaudo() {
        return this.laudo;
    }
    
    public void setLaudo(String laudo) {
        this.laudo = laudo;
    }

    
    @Column(name="tipo", nullable=false, length=15)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataExaImage", nullable=false, length=19)
    public Date getDataExaImage() {
        return this.dataExaImage;
    }
    
    public void setDataExaImage(Date dataExaImage) {
        this.dataExaImage = dataExaImage;
    }

    
    @Column(name="status", nullable=false, length=17)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="codExameImage", nullable=false, length=8)
    public String getCodExameImage() {
        return this.codExameImage;
    }
    
    public void setCodExameImage(String codExameImage) {
        this.codExameImage = codExameImage;
    }




}


