package com.lades.sihv.model;
// Generated 25/09/2018 14:47:05 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ExameImageId generated by hbm2java
 */
@Embeddable
public class ExameImageId  implements java.io.Serializable {


     private int pkExameImage;
     private int vetConsultationPkVetConsultation;

    public ExameImageId() {
    }

    public ExameImageId(int pkExameImage, int vetConsultationPkVetConsultation) {
       this.pkExameImage = pkExameImage;
       this.vetConsultationPkVetConsultation = vetConsultationPkVetConsultation;
    }
   


    @Column(name="PK_exameImage", nullable=false)
    public int getPkExameImage() {
        return this.pkExameImage;
    }
    
    public void setPkExameImage(int pkExameImage) {
        this.pkExameImage = pkExameImage;
    }


    @Column(name="vetConsultation_PK_vetConsultation", nullable=false)
    public int getVetConsultationPkVetConsultation() {
        return this.vetConsultationPkVetConsultation;
    }
    
    public void setVetConsultationPkVetConsultation(int vetConsultationPkVetConsultation) {
        this.vetConsultationPkVetConsultation = vetConsultationPkVetConsultation;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ExameImageId) ) return false;
		 ExameImageId castOther = ( ExameImageId ) other; 
         
		 return (this.getPkExameImage()==castOther.getPkExameImage())
 && (this.getVetConsultationPkVetConsultation()==castOther.getVetConsultationPkVetConsultation());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkExameImage();
         result = 37 * result + this.getVetConsultationPkVetConsultation();
         return result;
   }   


}


