package com.lades.sihv.model;
// Generated 09/11/2016 10:58:37 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ExameFisicoId generated by hbm2java
 */
@Embeddable
public class ExameFisicoId  implements java.io.Serializable {


     private int pkExameFisico;
     private int consultaFkConsulta;

    public ExameFisicoId() {
    }

    public ExameFisicoId(int pkExameFisico, int consultaFkConsulta) {
       this.pkExameFisico = pkExameFisico;
       this.consultaFkConsulta = consultaFkConsulta;
    }
   


    @Column(name="PK_exameFisico", nullable=false)
    public int getPkExameFisico() {
        return this.pkExameFisico;
    }
    
    public void setPkExameFisico(int pkExameFisico) {
        this.pkExameFisico = pkExameFisico;
    }


    @Column(name="consulta_FK_consulta", nullable=false)
    public int getConsultaFkConsulta() {
        return this.consultaFkConsulta;
    }
    
    public void setConsultaFkConsulta(int consultaFkConsulta) {
        this.consultaFkConsulta = consultaFkConsulta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ExameFisicoId) ) return false;
		 ExameFisicoId castOther = ( ExameFisicoId ) other; 
         
		 return (this.getPkExameFisico()==castOther.getPkExameFisico())
 && (this.getConsultaFkConsulta()==castOther.getConsultaFkConsulta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkExameFisico();
         result = 37 * result + this.getConsultaFkConsulta();
         return result;
   }   


}


