package com.lades.sihv.model;
// Generated 24/06/2018 11:35:04 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExameImage generated by hbm2java
 */
@Entity
@Table(name="exameImage"
    ,catalog="bd_sihv"
)
public class ExameImage  implements java.io.Serializable {


     private ExameImageId id;
     private Consulta consulta;
     private String regiExami;
     private String posicao;
     private Integer qtdChapas;
     private String laudo;
     private String tipo;
     private String statusExamImage;
     private String examImageCod;
     private Date atendimentoData;
     private Date solicitacaoData;

    public ExameImage() {
    }

	
    public ExameImage(ExameImageId id, Consulta consulta, String regiExami, String tipo, String statusExamImage, String examImageCod, Date solicitacaoData) {
        this.id = id;
        this.consulta = consulta;
        this.regiExami = regiExami;
        this.tipo = tipo;
        this.statusExamImage = statusExamImage;
        this.examImageCod = examImageCod;
        this.solicitacaoData = solicitacaoData;
    }
    public ExameImage(ExameImageId id, Consulta consulta, String regiExami, String posicao, Integer qtdChapas, String laudo, String tipo, String statusExamImage, String examImageCod, Date atendimentoData, Date solicitacaoData) {
       this.id = id;
       this.consulta = consulta;
       this.regiExami = regiExami;
       this.posicao = posicao;
       this.qtdChapas = qtdChapas;
       this.laudo = laudo;
       this.tipo = tipo;
       this.statusExamImage = statusExamImage;
       this.examImageCod = examImageCod;
       this.atendimentoData = atendimentoData;
       this.solicitacaoData = solicitacaoData;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pkExameImage", column=@Column(name="PK_exameImage", nullable=false) ), 
        @AttributeOverride(name="consultaFkConsulta", column=@Column(name="consulta_FK_consulta", nullable=false) ) } )
    public ExameImageId getId() {
        return this.id;
    }
    
    public void setId(ExameImageId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="consulta_FK_consulta", nullable=false, insertable=false, updatable=false)
    public Consulta getConsulta() {
        return this.consulta;
    }
    
    public void setConsulta(Consulta consulta) {
        this.consulta = consulta;
    }

    
    @Column(name="regiExami", nullable=false, length=254)
    public String getRegiExami() {
        return this.regiExami;
    }
    
    public void setRegiExami(String regiExami) {
        this.regiExami = regiExami;
    }

    
    @Column(name="posicao", length=50)
    public String getPosicao() {
        return this.posicao;
    }
    
    public void setPosicao(String posicao) {
        this.posicao = posicao;
    }

    
    @Column(name="qtdChapas")
    public Integer getQtdChapas() {
        return this.qtdChapas;
    }
    
    public void setQtdChapas(Integer qtdChapas) {
        this.qtdChapas = qtdChapas;
    }

    
    @Column(name="laudo", length=254)
    public String getLaudo() {
        return this.laudo;
    }
    
    public void setLaudo(String laudo) {
        this.laudo = laudo;
    }

    
    @Column(name="tipo", nullable=false, length=15)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="statusExamImage", nullable=false, length=17)
    public String getStatusExamImage() {
        return this.statusExamImage;
    }
    
    public void setStatusExamImage(String statusExamImage) {
        this.statusExamImage = statusExamImage;
    }

    
    @Column(name="examImageCod", nullable=false, length=100)
    public String getExamImageCod() {
        return this.examImageCod;
    }
    
    public void setExamImageCod(String examImageCod) {
        this.examImageCod = examImageCod;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="atendimentoData", length=19)
    public Date getAtendimentoData() {
        return this.atendimentoData;
    }
    
    public void setAtendimentoData(Date atendimentoData) {
        this.atendimentoData = atendimentoData;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="solicitacaoData", nullable=false, length=19)
    public Date getSolicitacaoData() {
        return this.solicitacaoData;
    }
    
    public void setSolicitacaoData(Date solicitacaoData) {
        this.solicitacaoData = solicitacaoData;
    }




}


