package com.lades.sihv.model;
// Generated 14/12/2016 15:34:50 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Fisica generated by hbm2java
 */
@Entity
@Table(name="fisica"
    ,catalog="bd_sihv"
)
public class Fisica  implements java.io.Serializable {


     private FisicaId id;
     private Pessoa pessoa;
     private String rg;
     private String sexo;

    public Fisica() {
    }

    public Fisica(FisicaId id, Pessoa pessoa, String rg, String sexo) {
       this.id = id;
       this.pessoa = pessoa;
       this.rg = rg;
       this.sexo = sexo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pkFisica", column=@Column(name="PK_fisica", nullable=false) ), 
        @AttributeOverride(name="fkPessoa", column=@Column(name="FK_pessoa", nullable=false) ) } )
    public FisicaId getId() {
        return this.id;
    }
    
    public void setId(FisicaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FK_pessoa", nullable=false, insertable=false, updatable=false)
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    
    @Column(name="rg", nullable=false, length=20)
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }

    
    @Column(name="sexo", nullable=false, length=3)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }




}


