package com.lades.sihv.model;
// Generated 04/10/2018 16:09:37 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GenreId generated by hbm2java
 */
@Embeddable
public class GenreId  implements java.io.Serializable {


     private int pkGenre;
     private int orderPkOrder;
     private int orderClassAnimalPkClassAnimal;

    public GenreId() {
    }

    public GenreId(int pkGenre, int orderPkOrder, int orderClassAnimalPkClassAnimal) {
       this.pkGenre = pkGenre;
       this.orderPkOrder = orderPkOrder;
       this.orderClassAnimalPkClassAnimal = orderClassAnimalPkClassAnimal;
    }
   


    @Column(name="PK_genre", nullable=false)
    public int getPkGenre() {
        return this.pkGenre;
    }
    
    public void setPkGenre(int pkGenre) {
        this.pkGenre = pkGenre;
    }


    @Column(name="order_PK_order", nullable=false)
    public int getOrderPkOrder() {
        return this.orderPkOrder;
    }
    
    public void setOrderPkOrder(int orderPkOrder) {
        this.orderPkOrder = orderPkOrder;
    }


    @Column(name="order_classAnimal_PK_classAnimal", nullable=false)
    public int getOrderClassAnimalPkClassAnimal() {
        return this.orderClassAnimalPkClassAnimal;
    }
    
    public void setOrderClassAnimalPkClassAnimal(int orderClassAnimalPkClassAnimal) {
        this.orderClassAnimalPkClassAnimal = orderClassAnimalPkClassAnimal;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GenreId) ) return false;
		 GenreId castOther = ( GenreId ) other; 
         
		 return (this.getPkGenre()==castOther.getPkGenre())
 && (this.getOrderPkOrder()==castOther.getOrderPkOrder())
 && (this.getOrderClassAnimalPkClassAnimal()==castOther.getOrderClassAnimalPkClassAnimal());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkGenre();
         result = 37 * result + this.getOrderPkOrder();
         result = 37 * result + this.getOrderClassAnimalPkClassAnimal();
         return result;
   }   


}


