package com.lades.sihv.model;
// Generated 04/10/2018 16:09:37 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Genre generated by hbm2java
 */
@Entity
@Table(name="genre"
    ,catalog="bd_sihv"
)
public class Genre  implements java.io.Serializable {


     private GenreId id;
     private Order order;
     private String genreName;
     private Date dataGenreRegister;
     private Set specieses = new HashSet(0);

    public Genre() {
    }

	
    public Genre(GenreId id, Order order, String genreName, Date dataGenreRegister) {
        this.id = id;
        this.order = order;
        this.genreName = genreName;
        this.dataGenreRegister = dataGenreRegister;
    }
    public Genre(GenreId id, Order order, String genreName, Date dataGenreRegister, Set specieses) {
       this.id = id;
       this.order = order;
       this.genreName = genreName;
       this.dataGenreRegister = dataGenreRegister;
       this.specieses = specieses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pkGenre", column=@Column(name="PK_genre", nullable=false) ), 
        @AttributeOverride(name="orderPkOrder", column=@Column(name="order_PK_order", nullable=false) ), 
        @AttributeOverride(name="orderClassAnimalPkClassAnimal", column=@Column(name="order_classAnimal_PK_classAnimal", nullable=false) ) } )
    public GenreId getId() {
        return this.id;
    }
    
    public void setId(GenreId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="order_PK_order", referencedColumnName="PK_order", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="order_classAnimal_PK_classAnimal", referencedColumnName="classAnimal_PK_classAnimal", nullable=false, insertable=false, updatable=false) } )
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }

    
    @Column(name="genreName", nullable=false, length=100)
    public String getGenreName() {
        return this.genreName;
    }
    
    public void setGenreName(String genreName) {
        this.genreName = genreName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataGenreRegister", nullable=false, length=19)
    public Date getDataGenreRegister() {
        return this.dataGenreRegister;
    }
    
    public void setDataGenreRegister(Date dataGenreRegister) {
        this.dataGenreRegister = dataGenreRegister;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="genre")
    public Set getSpecieses() {
        return this.specieses;
    }
    
    public void setSpecieses(Set specieses) {
        this.specieses = specieses;
    }




}


