package com.lades.sihv.model;
// Generated 04/10/2018 16:09:37 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hospitalization generated by hbm2java
 */
@Entity
@Table(name="hospitalization"
    ,catalog="bd_sihv"
)
public class Hospitalization  implements java.io.Serializable {


     private Integer pkHospitalization;
     private String reasonExitAnimal;
     private Date dateExitAnimal;
     private Date dataEntryAnimal;

    public Hospitalization() {
    }

	
    public Hospitalization(String reasonExitAnimal, Date dataEntryAnimal) {
        this.reasonExitAnimal = reasonExitAnimal;
        this.dataEntryAnimal = dataEntryAnimal;
    }
    public Hospitalization(String reasonExitAnimal, Date dateExitAnimal, Date dataEntryAnimal) {
       this.reasonExitAnimal = reasonExitAnimal;
       this.dateExitAnimal = dateExitAnimal;
       this.dataEntryAnimal = dataEntryAnimal;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_hospitalization", unique=true, nullable=false)
    public Integer getPkHospitalization() {
        return this.pkHospitalization;
    }
    
    public void setPkHospitalization(Integer pkHospitalization) {
        this.pkHospitalization = pkHospitalization;
    }

    
    @Column(name="reasonExitAnimal", nullable=false, length=45)
    public String getReasonExitAnimal() {
        return this.reasonExitAnimal;
    }
    
    public void setReasonExitAnimal(String reasonExitAnimal) {
        this.reasonExitAnimal = reasonExitAnimal;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateExitAnimal", length=10)
    public Date getDateExitAnimal() {
        return this.dateExitAnimal;
    }
    
    public void setDateExitAnimal(Date dateExitAnimal) {
        this.dateExitAnimal = dateExitAnimal;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataEntryAnimal", nullable=false, length=19)
    public Date getDataEntryAnimal() {
        return this.dataEntryAnimal;
    }
    
    public void setDataEntryAnimal(Date dataEntryAnimal) {
        this.dataEntryAnimal = dataEntryAnimal;
    }




}


