package com.lades.sihv.model;
// Generated 14/12/2016 15:34:50 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * JuridicaId generated by hbm2java
 */
@Embeddable
public class JuridicaId  implements java.io.Serializable {


     private int pkJuridica;
     private int fkPessoa;

    public JuridicaId() {
    }

    public JuridicaId(int pkJuridica, int fkPessoa) {
       this.pkJuridica = pkJuridica;
       this.fkPessoa = fkPessoa;
    }
   


    @Column(name="PK_juridica", nullable=false)
    public int getPkJuridica() {
        return this.pkJuridica;
    }
    
    public void setPkJuridica(int pkJuridica) {
        this.pkJuridica = pkJuridica;
    }


    @Column(name="FK_pessoa", nullable=false)
    public int getFkPessoa() {
        return this.fkPessoa;
    }
    
    public void setFkPessoa(int fkPessoa) {
        this.fkPessoa = fkPessoa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JuridicaId) ) return false;
		 JuridicaId castOther = ( JuridicaId ) other; 
         
		 return (this.getPkJuridica()==castOther.getPkJuridica())
 && (this.getFkPessoa()==castOther.getFkPessoa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkJuridica();
         result = 37 * result + this.getFkPessoa();
         return result;
   }   


}


