package com.lades.sihv.model;
// Generated 14/12/2016 15:34:50 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Juridica generated by hbm2java
 */
@Entity
@Table(name="juridica"
    ,catalog="bd_sihv"
)
public class Juridica  implements java.io.Serializable {


     private JuridicaId id;
     private Pessoa pessoa;
     private String tipoPessoaJuridica;

    public Juridica() {
    }

    public Juridica(JuridicaId id, Pessoa pessoa, String tipoPessoaJuridica) {
       this.id = id;
       this.pessoa = pessoa;
       this.tipoPessoaJuridica = tipoPessoaJuridica;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pkJuridica", column=@Column(name="PK_juridica", nullable=false) ), 
        @AttributeOverride(name="fkPessoa", column=@Column(name="FK_pessoa", nullable=false) ) } )
    public JuridicaId getId() {
        return this.id;
    }
    
    public void setId(JuridicaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FK_pessoa", nullable=false, insertable=false, updatable=false)
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    
    @Column(name="tipoPessoaJuridica", nullable=false, length=100)
    public String getTipoPessoaJuridica() {
        return this.tipoPessoaJuridica;
    }
    
    public void setTipoPessoaJuridica(String tipoPessoaJuridica) {
        this.tipoPessoaJuridica = tipoPessoaJuridica;
    }




}


