package com.lades.sihv.model;
// Generated 25/09/2018 14:47:05 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * LegalPerson generated by hbm2java
 */
@Entity
@Table(name="legalPerson"
    ,catalog="bd_sihv"
    , uniqueConstraints = @UniqueConstraint(columnNames="cnpj") 
)
public class LegalPerson  implements java.io.Serializable {


     private Integer pkLegalPerson;
     private People people;
     private String cnpj;
     private String descriptionEntity;

    public LegalPerson() {
    }

    public LegalPerson(People people, String cnpj, String descriptionEntity) {
       this.people = people;
       this.cnpj = cnpj;
       this.descriptionEntity = descriptionEntity;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_legalPerson", unique=true, nullable=false)
    public Integer getPkLegalPerson() {
        return this.pkLegalPerson;
    }
    
    public void setPkLegalPerson(Integer pkLegalPerson) {
        this.pkLegalPerson = pkLegalPerson;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="people_PK_person", nullable=false)
    public People getPeople() {
        return this.people;
    }
    
    public void setPeople(People people) {
        this.people = people;
    }

    
    @Column(name="cnpj", unique=true, nullable=false, length=18)
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }

    
    @Column(name="descriptionEntity", nullable=false, length=100)
    public String getDescriptionEntity() {
        return this.descriptionEntity;
    }
    
    public void setDescriptionEntity(String descriptionEntity) {
        this.descriptionEntity = descriptionEntity;
    }




}


