package com.lades.sihv.model;
// Generated 25/09/2018 14:47:05 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Nation generated by hbm2java
 */
@Entity
@Table(name="nation"
    ,catalog="bd_sihv"
)
public class Nation  implements java.io.Serializable {


     private Integer pkNation;
     private String fullNameNation;
     private String iso31661alpha2;
     private Date registrationDate;
     private Set federationUnities = new HashSet(0);

    public Nation() {
    }

	
    public Nation(String fullNameNation, String iso31661alpha2, Date registrationDate) {
        this.fullNameNation = fullNameNation;
        this.iso31661alpha2 = iso31661alpha2;
        this.registrationDate = registrationDate;
    }
    public Nation(String fullNameNation, String iso31661alpha2, Date registrationDate, Set federationUnities) {
       this.fullNameNation = fullNameNation;
       this.iso31661alpha2 = iso31661alpha2;
       this.registrationDate = registrationDate;
       this.federationUnities = federationUnities;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_nation", unique=true, nullable=false)
    public Integer getPkNation() {
        return this.pkNation;
    }
    
    public void setPkNation(Integer pkNation) {
        this.pkNation = pkNation;
    }

    
    @Column(name="fullNameNation", nullable=false, length=100)
    public String getFullNameNation() {
        return this.fullNameNation;
    }
    
    public void setFullNameNation(String fullNameNation) {
        this.fullNameNation = fullNameNation;
    }

    
    @Column(name="iso3166_1Alpha2", nullable=false, length=2)
    public String getIso31661alpha2() {
        return this.iso31661alpha2;
    }
    
    public void setIso31661alpha2(String iso31661alpha2) {
        this.iso31661alpha2 = iso31661alpha2;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="registrationDate", nullable=false, length=19)
    public Date getRegistrationDate() {
        return this.registrationDate;
    }
    
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nation")
    public Set getFederationUnities() {
        return this.federationUnities;
    }
    
    public void setFederationUnities(Set federationUnities) {
        this.federationUnities = federationUnities;
    }




}


