package com.lades.sihv.model;
// Generated 25/09/2018 14:47:05 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Neighborhood generated by hbm2java
 */
@Entity
@Table(name="neighborhood"
    ,catalog="bd_sihv"
)
public class Neighborhood  implements java.io.Serializable {


     private NeighborhoodId id;
     private City city;
     private String neighborhood;
     private Date registrationDate;
     private Set addresses = new HashSet(0);

    public Neighborhood() {
    }

	
    public Neighborhood(NeighborhoodId id, City city, String neighborhood, Date registrationDate) {
        this.id = id;
        this.city = city;
        this.neighborhood = neighborhood;
        this.registrationDate = registrationDate;
    }
    public Neighborhood(NeighborhoodId id, City city, String neighborhood, Date registrationDate, Set addresses) {
       this.id = id;
       this.city = city;
       this.neighborhood = neighborhood;
       this.registrationDate = registrationDate;
       this.addresses = addresses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pkNeighborhood", column=@Column(name="PK_neighborhood", nullable=false) ), 
        @AttributeOverride(name="cityPkCity", column=@Column(name="city_PK_city", nullable=false) ) } )
    public NeighborhoodId getId() {
        return this.id;
    }
    
    public void setId(NeighborhoodId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="city_PK_city", nullable=false, insertable=false, updatable=false)
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }

    
    @Column(name="neighborhood", nullable=false, length=100)
    public String getNeighborhood() {
        return this.neighborhood;
    }
    
    public void setNeighborhood(String neighborhood) {
        this.neighborhood = neighborhood;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="registrationDate", nullable=false, length=19)
    public Date getRegistrationDate() {
        return this.registrationDate;
    }
    
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="neighborhood")
    public Set getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set addresses) {
        this.addresses = addresses;
    }




}


