package com.lades.sihv.model;
// Generated 04/10/2018 16:09:37 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NonConventionalPet generated by hbm2java
 */
@Entity
@Table(name="nonConventionalPet"
    ,catalog="bd_sihv"
)
public class NonConventionalPet  implements java.io.Serializable {


     private Integer pkNonConventionalPet;

    public NonConventionalPet() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_nonConventionalPet", unique=true, nullable=false)
    public Integer getPkNonConventionalPet() {
        return this.pkNonConventionalPet;
    }
    
    public void setPkNonConventionalPet(Integer pkNonConventionalPet) {
        this.pkNonConventionalPet = pkNonConventionalPet;
    }




}


