package com.lades.sihv.model;
// Generated 04/10/2018 16:09:37 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name="order"
    ,catalog="bd_sihv"
)
public class Order  implements java.io.Serializable {


     private OrderId id;
     private ClassAnimal classAnimal;
     private String orderName;
     private Date dataOrderRegister;
     private Set genres = new HashSet(0);

    public Order() {
    }

	
    public Order(OrderId id, ClassAnimal classAnimal, String orderName, Date dataOrderRegister) {
        this.id = id;
        this.classAnimal = classAnimal;
        this.orderName = orderName;
        this.dataOrderRegister = dataOrderRegister;
    }
    public Order(OrderId id, ClassAnimal classAnimal, String orderName, Date dataOrderRegister, Set genres) {
       this.id = id;
       this.classAnimal = classAnimal;
       this.orderName = orderName;
       this.dataOrderRegister = dataOrderRegister;
       this.genres = genres;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pkOrder", column=@Column(name="PK_order", nullable=false) ), 
        @AttributeOverride(name="classAnimalPkClassAnimal", column=@Column(name="classAnimal_PK_classAnimal", nullable=false) ) } )
    public OrderId getId() {
        return this.id;
    }
    
    public void setId(OrderId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="classAnimal_PK_classAnimal", nullable=false, insertable=false, updatable=false)
    public ClassAnimal getClassAnimal() {
        return this.classAnimal;
    }
    
    public void setClassAnimal(ClassAnimal classAnimal) {
        this.classAnimal = classAnimal;
    }

    
    @Column(name="orderName", nullable=false, length=100)
    public String getOrderName() {
        return this.orderName;
    }
    
    public void setOrderName(String orderName) {
        this.orderName = orderName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataOrderRegister", nullable=false, length=19)
    public Date getDataOrderRegister() {
        return this.dataOrderRegister;
    }
    
    public void setDataOrderRegister(Date dataOrderRegister) {
        this.dataOrderRegister = dataOrderRegister;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="order")
    public Set getGenres() {
        return this.genres;
    }
    
    public void setGenres(Set genres) {
        this.genres = genres;
    }




}


