package com.lades.sihv.model;
// Generated 25/09/2018 14:47:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OwnersHasAnimals generated by hbm2java
 */
@Entity
@Table(name="ownersHasAnimals"
    ,catalog="bd_sihv"
)
public class OwnersHasAnimals  implements java.io.Serializable {


     private Integer pkOwnersHasAnimals;
     private Animals animals;
     private Owners owners;
     private Set vetConsultations = new HashSet(0);
     private Set schedulings = new HashSet(0);

    public OwnersHasAnimals() {
    }

	
    public OwnersHasAnimals(Animals animals, Owners owners) {
        this.animals = animals;
        this.owners = owners;
    }
    public OwnersHasAnimals(Animals animals, Owners owners, Set vetConsultations, Set schedulings) {
       this.animals = animals;
       this.owners = owners;
       this.vetConsultations = vetConsultations;
       this.schedulings = schedulings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_ownersHasAnimals", unique=true, nullable=false)
    public Integer getPkOwnersHasAnimals() {
        return this.pkOwnersHasAnimals;
    }
    
    public void setPkOwnersHasAnimals(Integer pkOwnersHasAnimals) {
        this.pkOwnersHasAnimals = pkOwnersHasAnimals;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="animals_PK_animal", nullable=false)
    public Animals getAnimals() {
        return this.animals;
    }
    
    public void setAnimals(Animals animals) {
        this.animals = animals;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="owners_PK_owner", nullable=false)
    public Owners getOwners() {
        return this.owners;
    }
    
    public void setOwners(Owners owners) {
        this.owners = owners;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ownersHasAnimals")
    public Set getVetConsultations() {
        return this.vetConsultations;
    }
    
    public void setVetConsultations(Set vetConsultations) {
        this.vetConsultations = vetConsultations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ownersHasAnimals")
    public Set getSchedulings() {
        return this.schedulings;
    }
    
    public void setSchedulings(Set schedulings) {
        this.schedulings = schedulings;
    }




}


