package com.lades.sihv.model;
// Generated 25/09/2018 14:47:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Owners generated by hbm2java
 */
@Entity
@Table(name="owners"
    ,catalog="bd_sihv"
)
public class Owners  implements java.io.Serializable {


     private Integer pkOwner;
     private People people;
     private Set ownersHasAnimalses = new HashSet(0);

    public Owners() {
    }

	
    public Owners(People people) {
        this.people = people;
    }
    public Owners(People people, Set ownersHasAnimalses) {
       this.people = people;
       this.ownersHasAnimalses = ownersHasAnimalses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_owner", unique=true, nullable=false)
    public Integer getPkOwner() {
        return this.pkOwner;
    }
    
    public void setPkOwner(Integer pkOwner) {
        this.pkOwner = pkOwner;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="people_PK_person", nullable=false)
    public People getPeople() {
        return this.people;
    }
    
    public void setPeople(People people) {
        this.people = people;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="owners")
    public Set getOwnersHasAnimalses() {
        return this.ownersHasAnimalses;
    }
    
    public void setOwnersHasAnimalses(Set ownersHasAnimalses) {
        this.ownersHasAnimalses = ownersHasAnimalses;
    }




}


