package com.lades.sihv.model;
// Generated 25/09/2018 14:47:05 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * People generated by hbm2java
 */
@Entity
@Table(name="people"
    ,catalog="bd_sihv"
)
public class People  implements java.io.Serializable {


     private Integer pkPerson;
     private String namePerson;
     private String email;
     private boolean logicalExclusion;
     private Date registrationDate;
     private Set userses = new HashSet(0);
     private Set houseses = new HashSet(0);
     private Set ownerses = new HashSet(0);
     private Set legalPersons = new HashSet(0);
     private Set physicalPersons = new HashSet(0);
     private Set phoneses = new HashSet(0);

    public People() {
    }

	
    public People(String namePerson, String email, boolean logicalExclusion, Date registrationDate) {
        this.namePerson = namePerson;
        this.email = email;
        this.logicalExclusion = logicalExclusion;
        this.registrationDate = registrationDate;
    }
    public People(String namePerson, String email, boolean logicalExclusion, Date registrationDate, Set userses, Set houseses, Set ownerses, Set legalPersons, Set physicalPersons, Set phoneses) {
       this.namePerson = namePerson;
       this.email = email;
       this.logicalExclusion = logicalExclusion;
       this.registrationDate = registrationDate;
       this.userses = userses;
       this.houseses = houseses;
       this.ownerses = ownerses;
       this.legalPersons = legalPersons;
       this.physicalPersons = physicalPersons;
       this.phoneses = phoneses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_person", unique=true, nullable=false)
    public Integer getPkPerson() {
        return this.pkPerson;
    }
    
    public void setPkPerson(Integer pkPerson) {
        this.pkPerson = pkPerson;
    }

    
    @Column(name="namePerson", nullable=false, length=100)
    public String getNamePerson() {
        return this.namePerson;
    }
    
    public void setNamePerson(String namePerson) {
        this.namePerson = namePerson;
    }

    
    @Column(name="email", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="logicalExclusion", nullable=false)
    public boolean isLogicalExclusion() {
        return this.logicalExclusion;
    }
    
    public void setLogicalExclusion(boolean logicalExclusion) {
        this.logicalExclusion = logicalExclusion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="registrationDate", nullable=false, length=19)
    public Date getRegistrationDate() {
        return this.registrationDate;
    }
    
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="people")
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="people")
    public Set getHouseses() {
        return this.houseses;
    }
    
    public void setHouseses(Set houseses) {
        this.houseses = houseses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="people")
    public Set getOwnerses() {
        return this.ownerses;
    }
    
    public void setOwnerses(Set ownerses) {
        this.ownerses = ownerses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="people")
    public Set getLegalPersons() {
        return this.legalPersons;
    }
    
    public void setLegalPersons(Set legalPersons) {
        this.legalPersons = legalPersons;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="people")
    public Set getPhysicalPersons() {
        return this.physicalPersons;
    }
    
    public void setPhysicalPersons(Set physicalPersons) {
        this.physicalPersons = physicalPersons;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="people")
    public Set getPhoneses() {
        return this.phoneses;
    }
    
    public void setPhoneses(Set phoneses) {
        this.phoneses = phoneses;
    }




}


