package com.lades.sihv.model;
// Generated 11/11/2016 14:03:19 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Pessoa generated by hbm2java
 */
@Entity
@Table(name="pessoa"
    ,catalog="bd_sihv"
    , uniqueConstraints = @UniqueConstraint(columnNames="cpf") 
)
public class Pessoa  implements java.io.Serializable {


     private Integer pkPessoa;
     private String cpf;
     private String rg;
     private String nome;
     private String sexo;
     private String logra;
     private String casaNumero;
     private String bairro;
     private String cidade;
     private String cep;
     private String complemento;
     private String uf;
     private Date cadDataHora;
     private Boolean exclusaoLogica;
     private String email;
     private Set<Telefone> telefones = new HashSet<Telefone>(0);
     private Set<Cliente> clientes = new HashSet<Cliente>(0);
     private Set<User> users = new HashSet<User>(0);

    public Pessoa() {
    }

	
    public Pessoa(String cpf, String rg, String nome, String sexo, String logra, String casaNumero, String bairro, String cidade, String cep, String uf, Date cadDataHora, String email) {
        this.cpf = cpf;
        this.rg = rg;
        this.nome = nome;
        this.sexo = sexo;
        this.logra = logra;
        this.casaNumero = casaNumero;
        this.bairro = bairro;
        this.cidade = cidade;
        this.cep = cep;
        this.uf = uf;
        this.cadDataHora = cadDataHora;
        this.email = email;
    }
    public Pessoa(String cpf, String rg, String nome, String sexo, String logra, String casaNumero, String bairro, String cidade, String cep, String complemento, String uf, Date cadDataHora, Boolean exclusaoLogica, String email, Set<Telefone> telefones, Set<Cliente> clientes, Set<User> users) {
       this.cpf = cpf;
       this.rg = rg;
       this.nome = nome;
       this.sexo = sexo;
       this.logra = logra;
       this.casaNumero = casaNumero;
       this.bairro = bairro;
       this.cidade = cidade;
       this.cep = cep;
       this.complemento = complemento;
       this.uf = uf;
       this.cadDataHora = cadDataHora;
       this.exclusaoLogica = exclusaoLogica;
       this.email = email;
       this.telefones = telefones;
       this.clientes = clientes;
       this.users = users;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_pessoa", unique=true, nullable=false)
    public Integer getPkPessoa() {
        return this.pkPessoa;
    }
    
    public void setPkPessoa(Integer pkPessoa) {
        this.pkPessoa = pkPessoa;
    }

    
    @Column(name="cpf", unique=true, nullable=false, length=18)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="rg", nullable=false, length=20)
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }

    
    @Column(name="nome", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="sexo", nullable=false, length=3)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    
    @Column(name="logra", nullable=false, length=100)
    public String getLogra() {
        return this.logra;
    }
    
    public void setLogra(String logra) {
        this.logra = logra;
    }

    
    @Column(name="casaNumero", nullable=false, length=7)
    public String getCasaNumero() {
        return this.casaNumero;
    }
    
    public void setCasaNumero(String casaNumero) {
        this.casaNumero = casaNumero;
    }

    
    @Column(name="bairro", nullable=false, length=100)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="cidade", nullable=false, length=100)
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="cep", nullable=false, length=9)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

    
    @Column(name="complemento", length=100)
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }

    
    @Column(name="uf", nullable=false, length=80)
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="cadDataHora", nullable=false, length=19)
    public Date getCadDataHora() {
        return this.cadDataHora;
    }
    
    public void setCadDataHora(Date cadDataHora) {
        this.cadDataHora = cadDataHora;
    }

    
    @Column(name="exclusaoLogica")
    public Boolean getExclusaoLogica() {
        return this.exclusaoLogica;
    }
    
    public void setExclusaoLogica(Boolean exclusaoLogica) {
        this.exclusaoLogica = exclusaoLogica;
    }

    
    @Column(name="email", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pessoa")
    public Set<Telefone> getTelefones() {
        return this.telefones;
    }
    
    public void setTelefones(Set<Telefone> telefones) {
        this.telefones = telefones;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pessoa")
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pessoa")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


