package com.lades.sihv.model;
// Generated 25/09/2018 14:47:05 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Phones generated by hbm2java
 */
@Entity
@Table(name="phones"
    ,catalog="bd_sihv"
)
public class Phones  implements java.io.Serializable {


     private Integer pkPhone;
     private People people;
     private String numberPhone;

    public Phones() {
    }

    public Phones(People people, String numberPhone) {
       this.people = people;
       this.numberPhone = numberPhone;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_phone", unique=true, nullable=false)
    public Integer getPkPhone() {
        return this.pkPhone;
    }
    
    public void setPkPhone(Integer pkPhone) {
        this.pkPhone = pkPhone;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="people_PK_person", nullable=false)
    public People getPeople() {
        return this.people;
    }
    
    public void setPeople(People people) {
        this.people = people;
    }

    
    @Column(name="numberPhone", nullable=false, length=15)
    public String getNumberPhone() {
        return this.numberPhone;
    }
    
    public void setNumberPhone(String numberPhone) {
        this.numberPhone = numberPhone;
    }




}


