package com.lades.sihv.model;
// Generated 25/09/2018 14:47:05 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PhysicalPersonId generated by hbm2java
 */
@Embeddable
public class PhysicalPersonId  implements java.io.Serializable {


     private int pkPhysicalPerson;
     private int peoplePkPerson;

    public PhysicalPersonId() {
    }

    public PhysicalPersonId(int pkPhysicalPerson, int peoplePkPerson) {
       this.pkPhysicalPerson = pkPhysicalPerson;
       this.peoplePkPerson = peoplePkPerson;
    }
   


    @Column(name="PK_physicalPerson", nullable=false)
    public int getPkPhysicalPerson() {
        return this.pkPhysicalPerson;
    }
    
    public void setPkPhysicalPerson(int pkPhysicalPerson) {
        this.pkPhysicalPerson = pkPhysicalPerson;
    }


    @Column(name="people_PK_person", nullable=false)
    public int getPeoplePkPerson() {
        return this.peoplePkPerson;
    }
    
    public void setPeoplePkPerson(int peoplePkPerson) {
        this.peoplePkPerson = peoplePkPerson;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PhysicalPersonId) ) return false;
		 PhysicalPersonId castOther = ( PhysicalPersonId ) other; 
         
		 return (this.getPkPhysicalPerson()==castOther.getPkPhysicalPerson())
 && (this.getPeoplePkPerson()==castOther.getPeoplePkPerson());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkPhysicalPerson();
         result = 37 * result + this.getPeoplePkPerson();
         return result;
   }   


}


