package com.lades.sihv.model;
// Generated 25/09/2018 14:47:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PhysicalPerson generated by hbm2java
 */
@Entity
@Table(name="physicalPerson"
    ,catalog="bd_sihv"
)
public class PhysicalPerson  implements java.io.Serializable {


     private PhysicalPersonId id;
     private People people;
     private String gender;
     private Set rgs = new HashSet(0);
     private Set cpfs = new HashSet(0);

    public PhysicalPerson() {
    }

	
    public PhysicalPerson(PhysicalPersonId id, People people, String gender) {
        this.id = id;
        this.people = people;
        this.gender = gender;
    }
    public PhysicalPerson(PhysicalPersonId id, People people, String gender, Set rgs, Set cpfs) {
       this.id = id;
       this.people = people;
       this.gender = gender;
       this.rgs = rgs;
       this.cpfs = cpfs;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pkPhysicalPerson", column=@Column(name="PK_physicalPerson", nullable=false) ), 
        @AttributeOverride(name="peoplePkPerson", column=@Column(name="people_PK_person", nullable=false) ) } )
    public PhysicalPersonId getId() {
        return this.id;
    }
    
    public void setId(PhysicalPersonId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="people_PK_person", nullable=false, insertable=false, updatable=false)
    public People getPeople() {
        return this.people;
    }
    
    public void setPeople(People people) {
        this.people = people;
    }

    
    @Column(name="gender", nullable=false, length=3)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="physicalPerson")
    public Set getRgs() {
        return this.rgs;
    }
    
    public void setRgs(Set rgs) {
        this.rgs = rgs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="physicalPerson")
    public Set getCpfs() {
        return this.cpfs;
    }
    
    public void setCpfs(Set cpfs) {
        this.cpfs = cpfs;
    }




}


