package com.lades.sihv.model;
// Generated 25/09/2018 14:47:05 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProceduresApplied generated by hbm2java
 */
@Entity
@Table(name="proceduresApplied"
    ,catalog="bd_sihv"
)
public class ProceduresApplied  implements java.io.Serializable {


     private ProceduresAppliedId id;
     private Procedures procedures;
     private VetConsultation vetConsultation;
     private Date applicationDate;

    public ProceduresApplied() {
    }

    public ProceduresApplied(ProceduresAppliedId id, Procedures procedures, VetConsultation vetConsultation, Date applicationDate) {
       this.id = id;
       this.procedures = procedures;
       this.vetConsultation = vetConsultation;
       this.applicationDate = applicationDate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="proceduresPkProcedure", column=@Column(name="procedures_PK_procedure", nullable=false) ), 
        @AttributeOverride(name="vetConsultationPkVetConsultation", column=@Column(name="vetConsultation_PK_vetConsultation", nullable=false) ) } )
    public ProceduresAppliedId getId() {
        return this.id;
    }
    
    public void setId(ProceduresAppliedId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="procedures_PK_procedure", nullable=false, insertable=false, updatable=false)
    public Procedures getProcedures() {
        return this.procedures;
    }
    
    public void setProcedures(Procedures procedures) {
        this.procedures = procedures;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vetConsultation_PK_vetConsultation", nullable=false, insertable=false, updatable=false)
    public VetConsultation getVetConsultation() {
        return this.vetConsultation;
    }
    
    public void setVetConsultation(VetConsultation vetConsultation) {
        this.vetConsultation = vetConsultation;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="applicationDate", nullable=false, length=19)
    public Date getApplicationDate() {
        return this.applicationDate;
    }
    
    public void setApplicationDate(Date applicationDate) {
        this.applicationDate = applicationDate;
    }




}


