package com.lades.sihv.model;
// Generated 02/11/2018 14:22:32 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Procedures generated by hbm2java
 */
@Entity
@Table(name="procedures"
    ,catalog="bd_sihv"
)
public class Procedures  implements java.io.Serializable {


     private Integer pkProcedure;
     private TypeProcedure typeProcedure;
     private String nameProcedure;
     private boolean disableProcedure;
     private Date dateOfLastModification;
     private Date dateOfFirstRegistration;
     private Prices prices;
     private Set proceduresApplieds = new HashSet(0);

    public Procedures() {
    }

	
    public Procedures(TypeProcedure typeProcedure, String nameProcedure, boolean disableProcedure, Date dateOfLastModification, Date dateOfFirstRegistration) {
        this.typeProcedure = typeProcedure;
        this.nameProcedure = nameProcedure;
        this.disableProcedure = disableProcedure;
        this.dateOfLastModification = dateOfLastModification;
        this.dateOfFirstRegistration = dateOfFirstRegistration;
    }
    public Procedures(TypeProcedure typeProcedure, String nameProcedure, boolean disableProcedure, Date dateOfLastModification, Date dateOfFirstRegistration, Prices prices, Set proceduresApplieds) {
       this.typeProcedure = typeProcedure;
       this.nameProcedure = nameProcedure;
       this.disableProcedure = disableProcedure;
       this.dateOfLastModification = dateOfLastModification;
       this.dateOfFirstRegistration = dateOfFirstRegistration;
       this.prices = prices;
       this.proceduresApplieds = proceduresApplieds;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_procedure", unique=true, nullable=false)
    public Integer getPkProcedure() {
        return this.pkProcedure;
    }
    
    public void setPkProcedure(Integer pkProcedure) {
        this.pkProcedure = pkProcedure;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="typeProcedure_PK_typeProcedure", nullable=false)
    public TypeProcedure getTypeProcedure() {
        return this.typeProcedure;
    }
    
    public void setTypeProcedure(TypeProcedure typeProcedure) {
        this.typeProcedure = typeProcedure;
    }

    
    @Column(name="nameProcedure", nullable=false, length=100)
    public String getNameProcedure() {
        return this.nameProcedure;
    }
    
    public void setNameProcedure(String nameProcedure) {
        this.nameProcedure = nameProcedure;
    }

    
    @Column(name="disableProcedure", nullable=false)
    public boolean isDisableProcedure() {
        return this.disableProcedure;
    }
    
    public void setDisableProcedure(boolean disableProcedure) {
        this.disableProcedure = disableProcedure;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateOfLastModification", nullable=false, length=10)
    public Date getDateOfLastModification() {
        return this.dateOfLastModification;
    }
    
    public void setDateOfLastModification(Date dateOfLastModification) {
        this.dateOfLastModification = dateOfLastModification;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateOfFirstRegistration", nullable=false, length=19)
    public Date getDateOfFirstRegistration() {
        return this.dateOfFirstRegistration;
    }
    
    public void setDateOfFirstRegistration(Date dateOfFirstRegistration) {
        this.dateOfFirstRegistration = dateOfFirstRegistration;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="procedures")
    public Prices getPrices() {
        return this.prices;
    }
    
    public void setPrices(Prices prices) {
        this.prices = prices;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="procedures")
    public Set getProceduresApplieds() {
        return this.proceduresApplieds;
    }
    
    public void setProceduresApplieds(Set proceduresApplieds) {
        this.proceduresApplieds = proceduresApplieds;
    }




}


