package com.lades.sihv.model;
// Generated 25/09/2018 14:47:05 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProceduresAppliedId generated by hbm2java
 */
@Embeddable
public class ProceduresAppliedId  implements java.io.Serializable {


     private int proceduresPkProcedure;
     private int vetConsultationPkVetConsultation;

    public ProceduresAppliedId() {
    }

    public ProceduresAppliedId(int proceduresPkProcedure, int vetConsultationPkVetConsultation) {
       this.proceduresPkProcedure = proceduresPkProcedure;
       this.vetConsultationPkVetConsultation = vetConsultationPkVetConsultation;
    }
   


    @Column(name="procedures_PK_procedure", nullable=false)
    public int getProceduresPkProcedure() {
        return this.proceduresPkProcedure;
    }
    
    public void setProceduresPkProcedure(int proceduresPkProcedure) {
        this.proceduresPkProcedure = proceduresPkProcedure;
    }


    @Column(name="vetConsultation_PK_vetConsultation", nullable=false)
    public int getVetConsultationPkVetConsultation() {
        return this.vetConsultationPkVetConsultation;
    }
    
    public void setVetConsultationPkVetConsultation(int vetConsultationPkVetConsultation) {
        this.vetConsultationPkVetConsultation = vetConsultationPkVetConsultation;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProceduresAppliedId) ) return false;
		 ProceduresAppliedId castOther = ( ProceduresAppliedId ) other; 
         
		 return (this.getProceduresPkProcedure()==castOther.getProceduresPkProcedure())
 && (this.getVetConsultationPkVetConsultation()==castOther.getVetConsultationPkVetConsultation());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProceduresPkProcedure();
         result = 37 * result + this.getVetConsultationPkVetConsultation();
         return result;
   }   


}


