package com.lades.sihv.model;
// Generated 14/12/2016 15:34:50 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Raca generated by hbm2java
 */
@Entity
@Table(name="raca"
    ,catalog="bd_sihv"
)
public class Raca  implements java.io.Serializable {


     private Integer pkRaca;
     private String nomeRaca;

    public Raca() {
    }

    public Raca(String nomeRaca) {
       this.nomeRaca = nomeRaca;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_raca", unique=true, nullable=false)
    public Integer getPkRaca() {
        return this.pkRaca;
    }
    
    public void setPkRaca(Integer pkRaca) {
        this.pkRaca = pkRaca;
    }

    
    @Column(name="nomeRaca", nullable=false, length=100)
    public String getNomeRaca() {
        return this.nomeRaca;
    }
    
    public void setNomeRaca(String nomeRaca) {
        this.nomeRaca = nomeRaca;
    }




}


