package com.lades.sihv.model;
// Generated 25/09/2018 14:47:05 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Rg generated by hbm2java
 */
@Entity
@Table(name="rg"
    ,catalog="bd_sihv"
)
public class Rg  implements java.io.Serializable {


     private RgId id;
     private PhysicalPerson physicalPerson;
     private String rg;

    public Rg() {
    }

    public Rg(RgId id, PhysicalPerson physicalPerson, String rg) {
       this.id = id;
       this.physicalPerson = physicalPerson;
       this.rg = rg;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pkRg", column=@Column(name="PK_rg", nullable=false) ), 
        @AttributeOverride(name="physicalPersonPkPhysicalPerson", column=@Column(name="physicalPerson_PK_physicalPerson", nullable=false) ), 
        @AttributeOverride(name="physicalPersonPeoplePkPerson", column=@Column(name="physicalPerson_people_PK_person", nullable=false) ) } )
    public RgId getId() {
        return this.id;
    }
    
    public void setId(RgId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="physicalPerson_PK_physicalPerson", referencedColumnName="PK_physicalPerson", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="physicalPerson_people_PK_person", referencedColumnName="people_PK_person", nullable=false, insertable=false, updatable=false) } )
    public PhysicalPerson getPhysicalPerson() {
        return this.physicalPerson;
    }
    
    public void setPhysicalPerson(PhysicalPerson physicalPerson) {
        this.physicalPerson = physicalPerson;
    }

    
    @Column(name="rg", nullable=false, length=20)
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }




}


