package com.lades.sihv.model;
// Generated 25/09/2018 14:47:05 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RgId generated by hbm2java
 */
@Embeddable
public class RgId  implements java.io.Serializable {


     private int pkRg;
     private int physicalPersonPkPhysicalPerson;
     private int physicalPersonPeoplePkPerson;

    public RgId() {
    }

    public RgId(int pkRg, int physicalPersonPkPhysicalPerson, int physicalPersonPeoplePkPerson) {
       this.pkRg = pkRg;
       this.physicalPersonPkPhysicalPerson = physicalPersonPkPhysicalPerson;
       this.physicalPersonPeoplePkPerson = physicalPersonPeoplePkPerson;
    }
   


    @Column(name="PK_rg", nullable=false)
    public int getPkRg() {
        return this.pkRg;
    }
    
    public void setPkRg(int pkRg) {
        this.pkRg = pkRg;
    }


    @Column(name="physicalPerson_PK_physicalPerson", nullable=false)
    public int getPhysicalPersonPkPhysicalPerson() {
        return this.physicalPersonPkPhysicalPerson;
    }
    
    public void setPhysicalPersonPkPhysicalPerson(int physicalPersonPkPhysicalPerson) {
        this.physicalPersonPkPhysicalPerson = physicalPersonPkPhysicalPerson;
    }


    @Column(name="physicalPerson_people_PK_person", nullable=false)
    public int getPhysicalPersonPeoplePkPerson() {
        return this.physicalPersonPeoplePkPerson;
    }
    
    public void setPhysicalPersonPeoplePkPerson(int physicalPersonPeoplePkPerson) {
        this.physicalPersonPeoplePkPerson = physicalPersonPeoplePkPerson;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RgId) ) return false;
		 RgId castOther = ( RgId ) other; 
         
		 return (this.getPkRg()==castOther.getPkRg())
 && (this.getPhysicalPersonPkPhysicalPerson()==castOther.getPhysicalPersonPkPhysicalPerson())
 && (this.getPhysicalPersonPeoplePkPerson()==castOther.getPhysicalPersonPeoplePkPerson());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkRg();
         result = 37 * result + this.getPhysicalPersonPkPhysicalPerson();
         result = 37 * result + this.getPhysicalPersonPeoplePkPerson();
         return result;
   }   


}


