package com.lades.sihv.model;
// Generated 01/08/2018 11:44:13 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Scheduling generated by hbm2java
 */
@Entity
@Table(name="scheduling"
    ,catalog="bd_sihv"
)
public class Scheduling  implements java.io.Serializable {


     private Integer pkSchedule;
     private Animais animais;
     private String typeService;
     private String statusService;
     private String registerClient;
     private Date schedulingDate;
     private Set consultas = new HashSet(0);
     private Set temporaryClientDatas = new HashSet(0);

    public Scheduling() {
    }

	
    public Scheduling(String typeService, String statusService, String registerClient, Date schedulingDate) {
        this.typeService = typeService;
        this.statusService = statusService;
        this.registerClient = registerClient;
        this.schedulingDate = schedulingDate;
    }
    public Scheduling(Animais animais, String typeService, String statusService, String registerClient, Date schedulingDate, Set consultas, Set temporaryClientDatas) {
       this.animais = animais;
       this.typeService = typeService;
       this.statusService = statusService;
       this.registerClient = registerClient;
       this.schedulingDate = schedulingDate;
       this.consultas = consultas;
       this.temporaryClientDatas = temporaryClientDatas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Pk_schedule", unique=true, nullable=false)
    public Integer getPkSchedule() {
        return this.pkSchedule;
    }
    
    public void setPkSchedule(Integer pkSchedule) {
        this.pkSchedule = pkSchedule;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="FK_animal", referencedColumnName="PK_animal"), 
        @JoinColumn(name="FK_cliente", referencedColumnName="FK_cliente"), 
        @JoinColumn(name="FK_pessoa", referencedColumnName="FK_pessoa") } )
    public Animais getAnimais() {
        return this.animais;
    }
    
    public void setAnimais(Animais animais) {
        this.animais = animais;
    }

    
    @Column(name="typeService", nullable=false, length=21)
    public String getTypeService() {
        return this.typeService;
    }
    
    public void setTypeService(String typeService) {
        this.typeService = typeService;
    }

    
    @Column(name="statusService", nullable=false, length=37)
    public String getStatusService() {
        return this.statusService;
    }
    
    public void setStatusService(String statusService) {
        this.statusService = statusService;
    }

    
    @Column(name="registerClient", nullable=false, length=15)
    public String getRegisterClient() {
        return this.registerClient;
    }
    
    public void setRegisterClient(String registerClient) {
        this.registerClient = registerClient;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="schedulingDate", nullable=false, length=19)
    public Date getSchedulingDate() {
        return this.schedulingDate;
    }
    
    public void setSchedulingDate(Date schedulingDate) {
        this.schedulingDate = schedulingDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="scheduling")
    public Set getConsultas() {
        return this.consultas;
    }
    
    public void setConsultas(Set consultas) {
        this.consultas = consultas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="scheduling")
    public Set getTemporaryClientDatas() {
        return this.temporaryClientDatas;
    }
    
    public void setTemporaryClientDatas(Set temporaryClientDatas) {
        this.temporaryClientDatas = temporaryClientDatas;
    }




}


