package com.lades.sihv.model;
// Generated 09/11/2016 10:58:37 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SisDigestorioId generated by hbm2java
 */
@Embeddable
public class SisDigestorioId  implements java.io.Serializable {


     private int pkSisDigestorio;
     private int consultaFkConsulta;

    public SisDigestorioId() {
    }

    public SisDigestorioId(int pkSisDigestorio, int consultaFkConsulta) {
       this.pkSisDigestorio = pkSisDigestorio;
       this.consultaFkConsulta = consultaFkConsulta;
    }
   


    @Column(name="PK_sisDigestorio", nullable=false)
    public int getPkSisDigestorio() {
        return this.pkSisDigestorio;
    }
    
    public void setPkSisDigestorio(int pkSisDigestorio) {
        this.pkSisDigestorio = pkSisDigestorio;
    }


    @Column(name="consulta_FK_consulta", nullable=false)
    public int getConsultaFkConsulta() {
        return this.consultaFkConsulta;
    }
    
    public void setConsultaFkConsulta(int consultaFkConsulta) {
        this.consultaFkConsulta = consultaFkConsulta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SisDigestorioId) ) return false;
		 SisDigestorioId castOther = ( SisDigestorioId ) other; 
         
		 return (this.getPkSisDigestorio()==castOther.getPkSisDigestorio())
 && (this.getConsultaFkConsulta()==castOther.getConsultaFkConsulta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkSisDigestorio();
         result = 37 * result + this.getConsultaFkConsulta();
         return result;
   }   


}


