package com.lades.sihv.model;
// Generated 25/09/2018 14:47:05 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SisDigestorioId generated by hbm2java
 */
@Embeddable
public class SisDigestorioId  implements java.io.Serializable {


     private int pkSisDigestorio;
     private int vetConsultationPkVetConsultation;

    public SisDigestorioId() {
    }

    public SisDigestorioId(int pkSisDigestorio, int vetConsultationPkVetConsultation) {
       this.pkSisDigestorio = pkSisDigestorio;
       this.vetConsultationPkVetConsultation = vetConsultationPkVetConsultation;
    }
   


    @Column(name="PK_sisDigestorio", nullable=false)
    public int getPkSisDigestorio() {
        return this.pkSisDigestorio;
    }
    
    public void setPkSisDigestorio(int pkSisDigestorio) {
        this.pkSisDigestorio = pkSisDigestorio;
    }


    @Column(name="vetConsultation_PK_vetConsultation", nullable=false)
    public int getVetConsultationPkVetConsultation() {
        return this.vetConsultationPkVetConsultation;
    }
    
    public void setVetConsultationPkVetConsultation(int vetConsultationPkVetConsultation) {
        this.vetConsultationPkVetConsultation = vetConsultationPkVetConsultation;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SisDigestorioId) ) return false;
		 SisDigestorioId castOther = ( SisDigestorioId ) other; 
         
		 return (this.getPkSisDigestorio()==castOther.getPkSisDigestorio())
 && (this.getVetConsultationPkVetConsultation()==castOther.getVetConsultationPkVetConsultation());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkSisDigestorio();
         result = 37 * result + this.getVetConsultationPkVetConsultation();
         return result;
   }   


}


