package com.lades.sihv.model;
// Generated 07/11/2016 13:25:44 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SisMuscEsqueId generated by hbm2java
 */
@Embeddable
public class SisMuscEsqueId  implements java.io.Serializable {


     private int pkSisMuscEsque;
     private int consultaFkConsulta;

    public SisMuscEsqueId() {
    }

    public SisMuscEsqueId(int pkSisMuscEsque, int consultaFkConsulta) {
       this.pkSisMuscEsque = pkSisMuscEsque;
       this.consultaFkConsulta = consultaFkConsulta;
    }
   


    @Column(name="PK_sisMuscEsque", nullable=false)
    public int getPkSisMuscEsque() {
        return this.pkSisMuscEsque;
    }
    
    public void setPkSisMuscEsque(int pkSisMuscEsque) {
        this.pkSisMuscEsque = pkSisMuscEsque;
    }


    @Column(name="consulta_FK_consulta", nullable=false)
    public int getConsultaFkConsulta() {
        return this.consultaFkConsulta;
    }
    
    public void setConsultaFkConsulta(int consultaFkConsulta) {
        this.consultaFkConsulta = consultaFkConsulta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SisMuscEsqueId) ) return false;
		 SisMuscEsqueId castOther = ( SisMuscEsqueId ) other; 
         
		 return (this.getPkSisMuscEsque()==castOther.getPkSisMuscEsque())
 && (this.getConsultaFkConsulta()==castOther.getConsultaFkConsulta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkSisMuscEsque();
         result = 37 * result + this.getConsultaFkConsulta();
         return result;
   }   


}


