package com.lades.sihv.model;
// Generated 28/10/2016 09:58:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SisNeurologicoId generated by hbm2java
 */
@Embeddable
public class SisNeurologicoId  implements java.io.Serializable {


     private int pkSisNeurologico;
     private int consultaPkConsulta;

    public SisNeurologicoId() {
    }

    public SisNeurologicoId(int pkSisNeurologico, int consultaPkConsulta) {
       this.pkSisNeurologico = pkSisNeurologico;
       this.consultaPkConsulta = consultaPkConsulta;
    }
   


    @Column(name="PK_Sis_Neurologico", nullable=false)
    public int getPkSisNeurologico() {
        return this.pkSisNeurologico;
    }
    
    public void setPkSisNeurologico(int pkSisNeurologico) {
        this.pkSisNeurologico = pkSisNeurologico;
    }


    @Column(name="consulta_PK_consulta", nullable=false)
    public int getConsultaPkConsulta() {
        return this.consultaPkConsulta;
    }
    
    public void setConsultaPkConsulta(int consultaPkConsulta) {
        this.consultaPkConsulta = consultaPkConsulta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SisNeurologicoId) ) return false;
		 SisNeurologicoId castOther = ( SisNeurologicoId ) other; 
         
		 return (this.getPkSisNeurologico()==castOther.getPkSisNeurologico())
 && (this.getConsultaPkConsulta()==castOther.getConsultaPkConsulta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkSisNeurologico();
         result = 37 * result + this.getConsultaPkConsulta();
         return result;
   }   


}


