package com.lades.sihv.model;
// Generated 25/09/2018 14:47:05 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SisNeurologicoId generated by hbm2java
 */
@Embeddable
public class SisNeurologicoId  implements java.io.Serializable {


     private int pkSisNeurologico;
     private int vetConsultationPkVetConsultation;

    public SisNeurologicoId() {
    }

    public SisNeurologicoId(int pkSisNeurologico, int vetConsultationPkVetConsultation) {
       this.pkSisNeurologico = pkSisNeurologico;
       this.vetConsultationPkVetConsultation = vetConsultationPkVetConsultation;
    }
   


    @Column(name="PK_sisNeurologico", nullable=false)
    public int getPkSisNeurologico() {
        return this.pkSisNeurologico;
    }
    
    public void setPkSisNeurologico(int pkSisNeurologico) {
        this.pkSisNeurologico = pkSisNeurologico;
    }


    @Column(name="vetConsultation_PK_vetConsultation", nullable=false)
    public int getVetConsultationPkVetConsultation() {
        return this.vetConsultationPkVetConsultation;
    }
    
    public void setVetConsultationPkVetConsultation(int vetConsultationPkVetConsultation) {
        this.vetConsultationPkVetConsultation = vetConsultationPkVetConsultation;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SisNeurologicoId) ) return false;
		 SisNeurologicoId castOther = ( SisNeurologicoId ) other; 
         
		 return (this.getPkSisNeurologico()==castOther.getPkSisNeurologico())
 && (this.getVetConsultationPkVetConsultation()==castOther.getVetConsultationPkVetConsultation());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkSisNeurologico();
         result = 37 * result + this.getVetConsultationPkVetConsultation();
         return result;
   }   


}


