package com.lades.sihv.model;
// Generated 28/10/2016 09:58:07 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SisNeurologico generated by hbm2java
 */
@Entity
@Table(name="Sis_Neurologico"
    ,catalog="BD_SIHV"
)
public class SisNeurologico  implements java.io.Serializable {


     private SisNeurologicoId id;
     private Consulta consulta;
     private String consciencia;
     private String comportamento;
     private String ataxia;
     private String ataxiaTipo;
     private String ataxiaEvolu;
     private String paralisia;
     private String paralisiaEspFla;
     private String paralisiaTipo;
     private String paralisiaEvolu;
     private String convulsao;
     private String convulsaoTipo;
     private String convulsaoEvolu;
     private String audicao;
     private String sistemaAfetado;

    public SisNeurologico() {
    }

	
    public SisNeurologico(SisNeurologicoId id, Consulta consulta, String consciencia, String comportamento, String ataxia, String paralisia, String convulsao, String audicao, String sistemaAfetado) {
        this.id = id;
        this.consulta = consulta;
        this.consciencia = consciencia;
        this.comportamento = comportamento;
        this.ataxia = ataxia;
        this.paralisia = paralisia;
        this.convulsao = convulsao;
        this.audicao = audicao;
        this.sistemaAfetado = sistemaAfetado;
    }
    public SisNeurologico(SisNeurologicoId id, Consulta consulta, String consciencia, String comportamento, String ataxia, String ataxiaTipo, String ataxiaEvolu, String paralisia, String paralisiaEspFla, String paralisiaTipo, String paralisiaEvolu, String convulsao, String convulsaoTipo, String convulsaoEvolu, String audicao, String sistemaAfetado) {
       this.id = id;
       this.consulta = consulta;
       this.consciencia = consciencia;
       this.comportamento = comportamento;
       this.ataxia = ataxia;
       this.ataxiaTipo = ataxiaTipo;
       this.ataxiaEvolu = ataxiaEvolu;
       this.paralisia = paralisia;
       this.paralisiaEspFla = paralisiaEspFla;
       this.paralisiaTipo = paralisiaTipo;
       this.paralisiaEvolu = paralisiaEvolu;
       this.convulsao = convulsao;
       this.convulsaoTipo = convulsaoTipo;
       this.convulsaoEvolu = convulsaoEvolu;
       this.audicao = audicao;
       this.sistemaAfetado = sistemaAfetado;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pkSisNeurologico", column=@Column(name="PK_Sis_Neurologico", nullable=false) ), 
        @AttributeOverride(name="consultaPkConsulta", column=@Column(name="consulta_PK_consulta", nullable=false) ) } )
    public SisNeurologicoId getId() {
        return this.id;
    }
    
    public void setId(SisNeurologicoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="consulta_PK_consulta", nullable=false, insertable=false, updatable=false)
    public Consulta getConsulta() {
        return this.consulta;
    }
    
    public void setConsulta(Consulta consulta) {
        this.consulta = consulta;
    }

    
    @Column(name="Consciencia", nullable=false, length=9)
    public String getConsciencia() {
        return this.consciencia;
    }
    
    public void setConsciencia(String consciencia) {
        this.consciencia = consciencia;
    }

    
    @Column(name="Comportamento", nullable=false, length=13)
    public String getComportamento() {
        return this.comportamento;
    }
    
    public void setComportamento(String comportamento) {
        this.comportamento = comportamento;
    }

    
    @Column(name="Ataxia", nullable=false, length=3)
    public String getAtaxia() {
        return this.ataxia;
    }
    
    public void setAtaxia(String ataxia) {
        this.ataxia = ataxia;
    }

    
    @Column(name="AtaxiaTipo", length=50)
    public String getAtaxiaTipo() {
        return this.ataxiaTipo;
    }
    
    public void setAtaxiaTipo(String ataxiaTipo) {
        this.ataxiaTipo = ataxiaTipo;
    }

    
    @Column(name="AtaxiaEvolu", length=200)
    public String getAtaxiaEvolu() {
        return this.ataxiaEvolu;
    }
    
    public void setAtaxiaEvolu(String ataxiaEvolu) {
        this.ataxiaEvolu = ataxiaEvolu;
    }

    
    @Column(name="Paralisia", nullable=false, length=3)
    public String getParalisia() {
        return this.paralisia;
    }
    
    public void setParalisia(String paralisia) {
        this.paralisia = paralisia;
    }

    
    @Column(name="ParalisiaEspFla", length=9)
    public String getParalisiaEspFla() {
        return this.paralisiaEspFla;
    }
    
    public void setParalisiaEspFla(String paralisiaEspFla) {
        this.paralisiaEspFla = paralisiaEspFla;
    }

    
    @Column(name="ParalisiaTipo", length=50)
    public String getParalisiaTipo() {
        return this.paralisiaTipo;
    }
    
    public void setParalisiaTipo(String paralisiaTipo) {
        this.paralisiaTipo = paralisiaTipo;
    }

    
    @Column(name="ParalisiaEvolu", length=200)
    public String getParalisiaEvolu() {
        return this.paralisiaEvolu;
    }
    
    public void setParalisiaEvolu(String paralisiaEvolu) {
        this.paralisiaEvolu = paralisiaEvolu;
    }

    
    @Column(name="Convulsao", nullable=false, length=3)
    public String getConvulsao() {
        return this.convulsao;
    }
    
    public void setConvulsao(String convulsao) {
        this.convulsao = convulsao;
    }

    
    @Column(name="ConvulsaoTipo", length=50)
    public String getConvulsaoTipo() {
        return this.convulsaoTipo;
    }
    
    public void setConvulsaoTipo(String convulsaoTipo) {
        this.convulsaoTipo = convulsaoTipo;
    }

    
    @Column(name="ConvulsaoEvolu", length=200)
    public String getConvulsaoEvolu() {
        return this.convulsaoEvolu;
    }
    
    public void setConvulsaoEvolu(String convulsaoEvolu) {
        this.convulsaoEvolu = convulsaoEvolu;
    }

    
    @Column(name="Audicao", nullable=false, length=6)
    public String getAudicao() {
        return this.audicao;
    }
    
    public void setAudicao(String audicao) {
        this.audicao = audicao;
    }

    
    @Column(name="SistemaAfetado", nullable=false, length=7)
    public String getSistemaAfetado() {
        return this.sistemaAfetado;
    }
    
    public void setSistemaAfetado(String sistemaAfetado) {
        this.sistemaAfetado = sistemaAfetado;
    }




}


