package com.lades.sihv.model;
// Generated 08/11/2016 12:03:42 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SisOftalmicoId generated by hbm2java
 */
@Embeddable
public class SisOftalmicoId  implements java.io.Serializable {


     private int pkSisOftalmico;
     private int consultaFkConsulta;

    public SisOftalmicoId() {
    }

    public SisOftalmicoId(int pkSisOftalmico, int consultaFkConsulta) {
       this.pkSisOftalmico = pkSisOftalmico;
       this.consultaFkConsulta = consultaFkConsulta;
    }
   


    @Column(name="PK_sisOftalmico", nullable=false)
    public int getPkSisOftalmico() {
        return this.pkSisOftalmico;
    }
    
    public void setPkSisOftalmico(int pkSisOftalmico) {
        this.pkSisOftalmico = pkSisOftalmico;
    }


    @Column(name="consulta_FK_consulta", nullable=false)
    public int getConsultaFkConsulta() {
        return this.consultaFkConsulta;
    }
    
    public void setConsultaFkConsulta(int consultaFkConsulta) {
        this.consultaFkConsulta = consultaFkConsulta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SisOftalmicoId) ) return false;
		 SisOftalmicoId castOther = ( SisOftalmicoId ) other; 
         
		 return (this.getPkSisOftalmico()==castOther.getPkSisOftalmico())
 && (this.getConsultaFkConsulta()==castOther.getConsultaFkConsulta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkSisOftalmico();
         result = 37 * result + this.getConsultaFkConsulta();
         return result;
   }   


}


