package com.lades.sihv.model;
// Generated 04/11/2016 14:35:29 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SisOftalmicoId generated by hbm2java
 */
@Embeddable
public class SisOftalmicoId  implements java.io.Serializable {


     private int pkSisOftalmico;
     private int consultaPkConsulta;

    public SisOftalmicoId() {
    }

    public SisOftalmicoId(int pkSisOftalmico, int consultaPkConsulta) {
       this.pkSisOftalmico = pkSisOftalmico;
       this.consultaPkConsulta = consultaPkConsulta;
    }
   


    @Column(name="PK_Sis_Oftalmico", nullable=false)
    public int getPkSisOftalmico() {
        return this.pkSisOftalmico;
    }
    
    public void setPkSisOftalmico(int pkSisOftalmico) {
        this.pkSisOftalmico = pkSisOftalmico;
    }


    @Column(name="consulta_PK_consulta", nullable=false)
    public int getConsultaPkConsulta() {
        return this.consultaPkConsulta;
    }
    
    public void setConsultaPkConsulta(int consultaPkConsulta) {
        this.consultaPkConsulta = consultaPkConsulta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SisOftalmicoId) ) return false;
		 SisOftalmicoId castOther = ( SisOftalmicoId ) other; 
         
		 return (this.getPkSisOftalmico()==castOther.getPkSisOftalmico())
 && (this.getConsultaPkConsulta()==castOther.getConsultaPkConsulta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkSisOftalmico();
         result = 37 * result + this.getConsultaPkConsulta();
         return result;
   }   


}


