package com.lades.sihv.model;
// Generated 28/10/2016 09:58:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SisRespCardioId generated by hbm2java
 */
@Embeddable
public class SisRespCardioId  implements java.io.Serializable {


     private int pkSisRespCardio;
     private int consultaPkConsulta;

    public SisRespCardioId() {
    }

    public SisRespCardioId(int pkSisRespCardio, int consultaPkConsulta) {
       this.pkSisRespCardio = pkSisRespCardio;
       this.consultaPkConsulta = consultaPkConsulta;
    }
   


    @Column(name="PK_Sis_Resp_Cardio", nullable=false)
    public int getPkSisRespCardio() {
        return this.pkSisRespCardio;
    }
    
    public void setPkSisRespCardio(int pkSisRespCardio) {
        this.pkSisRespCardio = pkSisRespCardio;
    }


    @Column(name="consulta_PK_consulta", nullable=false)
    public int getConsultaPkConsulta() {
        return this.consultaPkConsulta;
    }
    
    public void setConsultaPkConsulta(int consultaPkConsulta) {
        this.consultaPkConsulta = consultaPkConsulta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SisRespCardioId) ) return false;
		 SisRespCardioId castOther = ( SisRespCardioId ) other; 
         
		 return (this.getPkSisRespCardio()==castOther.getPkSisRespCardio())
 && (this.getConsultaPkConsulta()==castOther.getConsultaPkConsulta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkSisRespCardio();
         result = 37 * result + this.getConsultaPkConsulta();
         return result;
   }   


}


