package com.lades.sihv.model;
// Generated 14/06/2018 10:50:51 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SisRespCardio generated by hbm2java
 */
@Entity
@Table(name="sisRespCardio"
    ,catalog="bd_sihv"
)
public class SisRespCardio  implements java.io.Serializable {


     private SisRespCardioId id;
     private Consulta consulta;
     private String tosse;
     private String tosseProdutiva;
     private String tosseEvolu;
     private String espirro;
     private String espirroEvolu;
     private String secrecaoNasal;
     private String secreNasalUniBilateral;
     private String secreNasalTipo;
     private String secreNasalEvolu;
     private String dispneiaTaquipneia;
     private String dispnTaquipEvolu;
     private String cianose;
     private String cianoseEvolu;
     private String cansacoFacil;
     private String cansaFacilEvolu;
     private String sincope;
     private String sincopeEvolu;
     private String emagrecimento;
     private String emagrecEvolu;
     private String sistemaAfetado;

    public SisRespCardio() {
    }

	
    public SisRespCardio(SisRespCardioId id, Consulta consulta, String tosse, String espirro, String secrecaoNasal, String dispneiaTaquipneia, String cianose, String cansacoFacil, String sincope, String emagrecimento, String sistemaAfetado) {
        this.id = id;
        this.consulta = consulta;
        this.tosse = tosse;
        this.espirro = espirro;
        this.secrecaoNasal = secrecaoNasal;
        this.dispneiaTaquipneia = dispneiaTaquipneia;
        this.cianose = cianose;
        this.cansacoFacil = cansacoFacil;
        this.sincope = sincope;
        this.emagrecimento = emagrecimento;
        this.sistemaAfetado = sistemaAfetado;
    }
    public SisRespCardio(SisRespCardioId id, Consulta consulta, String tosse, String tosseProdutiva, String tosseEvolu, String espirro, String espirroEvolu, String secrecaoNasal, String secreNasalUniBilateral, String secreNasalTipo, String secreNasalEvolu, String dispneiaTaquipneia, String dispnTaquipEvolu, String cianose, String cianoseEvolu, String cansacoFacil, String cansaFacilEvolu, String sincope, String sincopeEvolu, String emagrecimento, String emagrecEvolu, String sistemaAfetado) {
       this.id = id;
       this.consulta = consulta;
       this.tosse = tosse;
       this.tosseProdutiva = tosseProdutiva;
       this.tosseEvolu = tosseEvolu;
       this.espirro = espirro;
       this.espirroEvolu = espirroEvolu;
       this.secrecaoNasal = secrecaoNasal;
       this.secreNasalUniBilateral = secreNasalUniBilateral;
       this.secreNasalTipo = secreNasalTipo;
       this.secreNasalEvolu = secreNasalEvolu;
       this.dispneiaTaquipneia = dispneiaTaquipneia;
       this.dispnTaquipEvolu = dispnTaquipEvolu;
       this.cianose = cianose;
       this.cianoseEvolu = cianoseEvolu;
       this.cansacoFacil = cansacoFacil;
       this.cansaFacilEvolu = cansaFacilEvolu;
       this.sincope = sincope;
       this.sincopeEvolu = sincopeEvolu;
       this.emagrecimento = emagrecimento;
       this.emagrecEvolu = emagrecEvolu;
       this.sistemaAfetado = sistemaAfetado;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pkSisRespCardio", column=@Column(name="PK_sisRespCardio", nullable=false) ), 
        @AttributeOverride(name="consultaFkConsulta", column=@Column(name="consulta_FK_consulta", nullable=false) ) } )
    public SisRespCardioId getId() {
        return this.id;
    }
    
    public void setId(SisRespCardioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="consulta_FK_consulta", nullable=false, insertable=false, updatable=false)
    public Consulta getConsulta() {
        return this.consulta;
    }
    
    public void setConsulta(Consulta consulta) {
        this.consulta = consulta;
    }

    
    @Column(name="tosse", nullable=false, length=7)
    public String getTosse() {
        return this.tosse;
    }
    
    public void setTosse(String tosse) {
        this.tosse = tosse;
    }

    
    @Column(name="tosseProdutiva", length=30)
    public String getTosseProdutiva() {
        return this.tosseProdutiva;
    }
    
    public void setTosseProdutiva(String tosseProdutiva) {
        this.tosseProdutiva = tosseProdutiva;
    }

    
    @Column(name="tosseEvolu", length=200)
    public String getTosseEvolu() {
        return this.tosseEvolu;
    }
    
    public void setTosseEvolu(String tosseEvolu) {
        this.tosseEvolu = tosseEvolu;
    }

    
    @Column(name="espirro", nullable=false, length=7)
    public String getEspirro() {
        return this.espirro;
    }
    
    public void setEspirro(String espirro) {
        this.espirro = espirro;
    }

    
    @Column(name="espirroEvolu", length=200)
    public String getEspirroEvolu() {
        return this.espirroEvolu;
    }
    
    public void setEspirroEvolu(String espirroEvolu) {
        this.espirroEvolu = espirroEvolu;
    }

    
    @Column(name="secrecaoNasal", nullable=false, length=7)
    public String getSecrecaoNasal() {
        return this.secrecaoNasal;
    }
    
    public void setSecrecaoNasal(String secrecaoNasal) {
        this.secrecaoNasal = secrecaoNasal;
    }

    
    @Column(name="secreNasalUniBilateral", length=57)
    public String getSecreNasalUniBilateral() {
        return this.secreNasalUniBilateral;
    }
    
    public void setSecreNasalUniBilateral(String secreNasalUniBilateral) {
        this.secreNasalUniBilateral = secreNasalUniBilateral;
    }

    
    @Column(name="secreNasalTipo", length=50)
    public String getSecreNasalTipo() {
        return this.secreNasalTipo;
    }
    
    public void setSecreNasalTipo(String secreNasalTipo) {
        this.secreNasalTipo = secreNasalTipo;
    }

    
    @Column(name="secreNasalEvolu", length=200)
    public String getSecreNasalEvolu() {
        return this.secreNasalEvolu;
    }
    
    public void setSecreNasalEvolu(String secreNasalEvolu) {
        this.secreNasalEvolu = secreNasalEvolu;
    }

    
    @Column(name="dispneiaTaquipneia", nullable=false, length=7)
    public String getDispneiaTaquipneia() {
        return this.dispneiaTaquipneia;
    }
    
    public void setDispneiaTaquipneia(String dispneiaTaquipneia) {
        this.dispneiaTaquipneia = dispneiaTaquipneia;
    }

    
    @Column(name="dispnTaquipEvolu", length=200)
    public String getDispnTaquipEvolu() {
        return this.dispnTaquipEvolu;
    }
    
    public void setDispnTaquipEvolu(String dispnTaquipEvolu) {
        this.dispnTaquipEvolu = dispnTaquipEvolu;
    }

    
    @Column(name="cianose", nullable=false, length=7)
    public String getCianose() {
        return this.cianose;
    }
    
    public void setCianose(String cianose) {
        this.cianose = cianose;
    }

    
    @Column(name="cianoseEvolu", length=200)
    public String getCianoseEvolu() {
        return this.cianoseEvolu;
    }
    
    public void setCianoseEvolu(String cianoseEvolu) {
        this.cianoseEvolu = cianoseEvolu;
    }

    
    @Column(name="cansacoFacil", nullable=false, length=7)
    public String getCansacoFacil() {
        return this.cansacoFacil;
    }
    
    public void setCansacoFacil(String cansacoFacil) {
        this.cansacoFacil = cansacoFacil;
    }

    
    @Column(name="cansaFacilEvolu", length=200)
    public String getCansaFacilEvolu() {
        return this.cansaFacilEvolu;
    }
    
    public void setCansaFacilEvolu(String cansaFacilEvolu) {
        this.cansaFacilEvolu = cansaFacilEvolu;
    }

    
    @Column(name="sincope", nullable=false, length=7)
    public String getSincope() {
        return this.sincope;
    }
    
    public void setSincope(String sincope) {
        this.sincope = sincope;
    }

    
    @Column(name="sincopeEvolu", length=200)
    public String getSincopeEvolu() {
        return this.sincopeEvolu;
    }
    
    public void setSincopeEvolu(String sincopeEvolu) {
        this.sincopeEvolu = sincopeEvolu;
    }

    
    @Column(name="emagrecimento", nullable=false, length=7)
    public String getEmagrecimento() {
        return this.emagrecimento;
    }
    
    public void setEmagrecimento(String emagrecimento) {
        this.emagrecimento = emagrecimento;
    }

    
    @Column(name="emagrecEvolu", length=200)
    public String getEmagrecEvolu() {
        return this.emagrecEvolu;
    }
    
    public void setEmagrecEvolu(String emagrecEvolu) {
        this.emagrecEvolu = emagrecEvolu;
    }

    
    @Column(name="sistemaAfetado", nullable=false, length=7)
    public String getSistemaAfetado() {
        return this.sistemaAfetado;
    }
    
    public void setSistemaAfetado(String sistemaAfetado) {
        this.sistemaAfetado = sistemaAfetado;
    }




}


