package com.lades.sihv.model;
// Generated 28/10/2016 09:58:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SisTegumentarId generated by hbm2java
 */
@Embeddable
public class SisTegumentarId  implements java.io.Serializable {


     private int pkSisTegumentar;
     private int consultaPkConsulta;

    public SisTegumentarId() {
    }

    public SisTegumentarId(int pkSisTegumentar, int consultaPkConsulta) {
       this.pkSisTegumentar = pkSisTegumentar;
       this.consultaPkConsulta = consultaPkConsulta;
    }
   


    @Column(name="PK_Sis_Tegumentar", nullable=false)
    public int getPkSisTegumentar() {
        return this.pkSisTegumentar;
    }
    
    public void setPkSisTegumentar(int pkSisTegumentar) {
        this.pkSisTegumentar = pkSisTegumentar;
    }


    @Column(name="consulta_PK_consulta", nullable=false)
    public int getConsultaPkConsulta() {
        return this.consultaPkConsulta;
    }
    
    public void setConsultaPkConsulta(int consultaPkConsulta) {
        this.consultaPkConsulta = consultaPkConsulta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SisTegumentarId) ) return false;
		 SisTegumentarId castOther = ( SisTegumentarId ) other; 
         
		 return (this.getPkSisTegumentar()==castOther.getPkSisTegumentar())
 && (this.getConsultaPkConsulta()==castOther.getConsultaPkConsulta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkSisTegumentar();
         result = 37 * result + this.getConsultaPkConsulta();
         return result;
   }   


}


