package com.lades.sihv.model;
// Generated 25/09/2018 14:47:05 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SisTegumentarId generated by hbm2java
 */
@Embeddable
public class SisTegumentarId  implements java.io.Serializable {


     private int pkSisTegumentar;
     private int vetConsultationPkVetConsultation;

    public SisTegumentarId() {
    }

    public SisTegumentarId(int pkSisTegumentar, int vetConsultationPkVetConsultation) {
       this.pkSisTegumentar = pkSisTegumentar;
       this.vetConsultationPkVetConsultation = vetConsultationPkVetConsultation;
    }
   


    @Column(name="PK_sisTegumentar", nullable=false)
    public int getPkSisTegumentar() {
        return this.pkSisTegumentar;
    }
    
    public void setPkSisTegumentar(int pkSisTegumentar) {
        this.pkSisTegumentar = pkSisTegumentar;
    }


    @Column(name="vetConsultation_PK_vetConsultation", nullable=false)
    public int getVetConsultationPkVetConsultation() {
        return this.vetConsultationPkVetConsultation;
    }
    
    public void setVetConsultationPkVetConsultation(int vetConsultationPkVetConsultation) {
        this.vetConsultationPkVetConsultation = vetConsultationPkVetConsultation;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SisTegumentarId) ) return false;
		 SisTegumentarId castOther = ( SisTegumentarId ) other; 
         
		 return (this.getPkSisTegumentar()==castOther.getPkSisTegumentar())
 && (this.getVetConsultationPkVetConsultation()==castOther.getVetConsultationPkVetConsultation());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkSisTegumentar();
         result = 37 * result + this.getVetConsultationPkVetConsultation();
         return result;
   }   


}


