package com.lades.sihv.model;
// Generated 25/09/2018 14:47:05 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Species generated by hbm2java
 */
@Entity
@Table(name="species"
    ,catalog="bd_sihv"
)
public class Species  implements java.io.Serializable {


     private SpeciesId id;
     private ClassAnimal classAnimal;
     private String nameSpecies;
     private Date dataSpeciesRegister;
     private Set raceses = new HashSet(0);

    public Species() {
    }

	
    public Species(SpeciesId id, ClassAnimal classAnimal, String nameSpecies, Date dataSpeciesRegister) {
        this.id = id;
        this.classAnimal = classAnimal;
        this.nameSpecies = nameSpecies;
        this.dataSpeciesRegister = dataSpeciesRegister;
    }
    public Species(SpeciesId id, ClassAnimal classAnimal, String nameSpecies, Date dataSpeciesRegister, Set raceses) {
       this.id = id;
       this.classAnimal = classAnimal;
       this.nameSpecies = nameSpecies;
       this.dataSpeciesRegister = dataSpeciesRegister;
       this.raceses = raceses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pkSpecies", column=@Column(name="PK_species", nullable=false) ), 
        @AttributeOverride(name="classAnimalPkClassAnimal", column=@Column(name="classAnimal_PK_classAnimal", nullable=false) ) } )
    public SpeciesId getId() {
        return this.id;
    }
    
    public void setId(SpeciesId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="classAnimal_PK_classAnimal", nullable=false, insertable=false, updatable=false)
    public ClassAnimal getClassAnimal() {
        return this.classAnimal;
    }
    
    public void setClassAnimal(ClassAnimal classAnimal) {
        this.classAnimal = classAnimal;
    }

    
    @Column(name="nameSpecies", nullable=false, length=100)
    public String getNameSpecies() {
        return this.nameSpecies;
    }
    
    public void setNameSpecies(String nameSpecies) {
        this.nameSpecies = nameSpecies;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataSpeciesRegister", nullable=false, length=19)
    public Date getDataSpeciesRegister() {
        return this.dataSpeciesRegister;
    }
    
    public void setDataSpeciesRegister(Date dataSpeciesRegister) {
        this.dataSpeciesRegister = dataSpeciesRegister;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="species")
    public Set getRaceses() {
        return this.raceses;
    }
    
    public void setRaceses(Set raceses) {
        this.raceses = raceses;
    }




}


