package com.lades.sihv.model;
// Generated 01/08/2018 11:44:13 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Species generated by hbm2java
 */
@Entity
@Table(name="species"
    ,catalog="bd_sihv"
)
public class Species  implements java.io.Serializable {


     private Integer pkSpecies;
     private String nameSpecies;
     private Date dataSpeciesRegister;
     private Set raceses = new HashSet(0);

    public Species() {
    }

	
    public Species(String nameSpecies, Date dataSpeciesRegister) {
        this.nameSpecies = nameSpecies;
        this.dataSpeciesRegister = dataSpeciesRegister;
    }
    public Species(String nameSpecies, Date dataSpeciesRegister, Set raceses) {
       this.nameSpecies = nameSpecies;
       this.dataSpeciesRegister = dataSpeciesRegister;
       this.raceses = raceses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_species", unique=true, nullable=false)
    public Integer getPkSpecies() {
        return this.pkSpecies;
    }
    
    public void setPkSpecies(Integer pkSpecies) {
        this.pkSpecies = pkSpecies;
    }

    
    @Column(name="nameSpecies", nullable=false, length=100)
    public String getNameSpecies() {
        return this.nameSpecies;
    }
    
    public void setNameSpecies(String nameSpecies) {
        this.nameSpecies = nameSpecies;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataSpeciesRegister", nullable=false, length=19)
    public Date getDataSpeciesRegister() {
        return this.dataSpeciesRegister;
    }
    
    public void setDataSpeciesRegister(Date dataSpeciesRegister) {
        this.dataSpeciesRegister = dataSpeciesRegister;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="species")
    public Set getRaceses() {
        return this.raceses;
    }
    
    public void setRaceses(Set raceses) {
        this.raceses = raceses;
    }




}


