package com.lades.sihv.model;
// Generated 04/10/2018 16:09:37 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sylvan generated by hbm2java
 */
@Entity
@Table(name="sylvan"
    ,catalog="bd_sihv"
)
public class Sylvan  implements java.io.Serializable {


     private Integer pkSylvan;
     private String typeAnimal;

    public Sylvan() {
    }

    public Sylvan(String typeAnimal) {
       this.typeAnimal = typeAnimal;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_sylvan", unique=true, nullable=false)
    public Integer getPkSylvan() {
        return this.pkSylvan;
    }
    
    public void setPkSylvan(Integer pkSylvan) {
        this.pkSylvan = pkSylvan;
    }

    
    @Column(name="typeAnimal", nullable=false, length=30)
    public String getTypeAnimal() {
        return this.typeAnimal;
    }
    
    public void setTypeAnimal(String typeAnimal) {
        this.typeAnimal = typeAnimal;
    }




}


