package com.lades.sihv.model;
// Generated 09/11/2016 10:58:37 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Telefone generated by hbm2java
 */
@Entity
@Table(name="telefone"
    ,catalog="bd_sihv"
)
public class Telefone  implements java.io.Serializable {


     private Integer pkTelefone;
     private Pessoa pessoa;
     private String numero;

    public Telefone() {
    }

    public Telefone(Pessoa pessoa, String numero) {
       this.pessoa = pessoa;
       this.numero = numero;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_telefone", unique=true, nullable=false)
    public Integer getPkTelefone() {
        return this.pkTelefone;
    }
    
    public void setPkTelefone(Integer pkTelefone) {
        this.pkTelefone = pkTelefone;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FK_pessoa", nullable=false)
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    
    @Column(name="numero", nullable=false, length=15)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }




}


