package com.lades.sihv.model;
// Generated 01/08/2018 11:44:13 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TemporaryClientData generated by hbm2java
 */
@Entity
@Table(name="temporaryClientData"
    ,catalog="bd_sihv"
)
public class TemporaryClientData  implements java.io.Serializable {


     private Integer pkTempCliData;
     private Scheduling scheduling;
     private String proprietaryName;
     private String animalName;
     private String proprietaryPhones;

    public TemporaryClientData() {
    }

    public TemporaryClientData(Scheduling scheduling, String proprietaryName, String animalName, String proprietaryPhones) {
       this.scheduling = scheduling;
       this.proprietaryName = proprietaryName;
       this.animalName = animalName;
       this.proprietaryPhones = proprietaryPhones;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_tempCliData", unique=true, nullable=false)
    public Integer getPkTempCliData() {
        return this.pkTempCliData;
    }
    
    public void setPkTempCliData(Integer pkTempCliData) {
        this.pkTempCliData = pkTempCliData;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FK_schedule", nullable=false)
    public Scheduling getScheduling() {
        return this.scheduling;
    }
    
    public void setScheduling(Scheduling scheduling) {
        this.scheduling = scheduling;
    }

    
    @Column(name="proprietaryName", nullable=false, length=100)
    public String getProprietaryName() {
        return this.proprietaryName;
    }
    
    public void setProprietaryName(String proprietaryName) {
        this.proprietaryName = proprietaryName;
    }

    
    @Column(name="animalName", nullable=false, length=70)
    public String getAnimalName() {
        return this.animalName;
    }
    
    public void setAnimalName(String animalName) {
        this.animalName = animalName;
    }

    
    @Column(name="proprietaryPhones", nullable=false, length=50)
    public String getProprietaryPhones() {
        return this.proprietaryPhones;
    }
    
    public void setProprietaryPhones(String proprietaryPhones) {
        this.proprietaryPhones = proprietaryPhones;
    }




}


