package com.lades.sihv.model;
// Generated 02/11/2018 14:22:32 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TypeProcedure generated by hbm2java
 */
@Entity
@Table(name="typeProcedure"
    ,catalog="bd_sihv"
)
public class TypeProcedure  implements java.io.Serializable {


     private Integer pkTypeProcedure;
     private String nameTypeProced;
     private boolean logicalExclusion;
     private Date dateOfFirstRegistration;
     private Set procedureses = new HashSet(0);

    public TypeProcedure() {
    }

	
    public TypeProcedure(String nameTypeProced, boolean logicalExclusion, Date dateOfFirstRegistration) {
        this.nameTypeProced = nameTypeProced;
        this.logicalExclusion = logicalExclusion;
        this.dateOfFirstRegistration = dateOfFirstRegistration;
    }
    public TypeProcedure(String nameTypeProced, boolean logicalExclusion, Date dateOfFirstRegistration, Set procedureses) {
       this.nameTypeProced = nameTypeProced;
       this.logicalExclusion = logicalExclusion;
       this.dateOfFirstRegistration = dateOfFirstRegistration;
       this.procedureses = procedureses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_typeProcedure", unique=true, nullable=false)
    public Integer getPkTypeProcedure() {
        return this.pkTypeProcedure;
    }
    
    public void setPkTypeProcedure(Integer pkTypeProcedure) {
        this.pkTypeProcedure = pkTypeProcedure;
    }

    
    @Column(name="nameTypeProced", nullable=false, length=100)
    public String getNameTypeProced() {
        return this.nameTypeProced;
    }
    
    public void setNameTypeProced(String nameTypeProced) {
        this.nameTypeProced = nameTypeProced;
    }

    
    @Column(name="logicalExclusion", nullable=false)
    public boolean isLogicalExclusion() {
        return this.logicalExclusion;
    }
    
    public void setLogicalExclusion(boolean logicalExclusion) {
        this.logicalExclusion = logicalExclusion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateOfFirstRegistration", nullable=false, length=19)
    public Date getDateOfFirstRegistration() {
        return this.dateOfFirstRegistration;
    }
    
    public void setDateOfFirstRegistration(Date dateOfFirstRegistration) {
        this.dateOfFirstRegistration = dateOfFirstRegistration;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="typeProcedure")
    public Set getProcedureses() {
        return this.procedureses;
    }
    
    public void setProcedureses(Set procedureses) {
        this.procedureses = procedureses;
    }




}


