package com.lades.sihv.model;
// Generated 25/09/2018 14:47:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeProcedure generated by hbm2java
 */
@Entity
@Table(name="typeProcedure"
    ,catalog="bd_sihv"
)
public class TypeProcedure  implements java.io.Serializable {


     private Integer pkTypeProcedure;
     private String nameTypeProced;
     private Set procedureses = new HashSet(0);

    public TypeProcedure() {
    }

	
    public TypeProcedure(String nameTypeProced) {
        this.nameTypeProced = nameTypeProced;
    }
    public TypeProcedure(String nameTypeProced, Set procedureses) {
       this.nameTypeProced = nameTypeProced;
       this.procedureses = procedureses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_typeProcedure", unique=true, nullable=false)
    public Integer getPkTypeProcedure() {
        return this.pkTypeProcedure;
    }
    
    public void setPkTypeProcedure(Integer pkTypeProcedure) {
        this.pkTypeProcedure = pkTypeProcedure;
    }

    
    @Column(name="nameTypeProced", nullable=false, length=100)
    public String getNameTypeProced() {
        return this.nameTypeProced;
    }
    
    public void setNameTypeProced(String nameTypeProced) {
        this.nameTypeProced = nameTypeProced;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="typeProcedure")
    public Set getProcedureses() {
        return this.procedureses;
    }
    
    public void setProcedureses(Set procedureses) {
        this.procedureses = procedureses;
    }




}


