package com.lades.sihv.model;
// Generated 08/11/2016 12:03:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="bd_sihv"
    , uniqueConstraints = @UniqueConstraint(columnNames="crmvMatricula") 
)
public class User  implements java.io.Serializable {


     private UserId id;
     private Pessoa pessoa;
     private String userNick;
     private String userSenha;
     private String userTipo;
     private String crmvMatricula;
     private Set<Consulta> consultas = new HashSet<Consulta>(0);

    public User() {
    }

	
    public User(UserId id, Pessoa pessoa, String userNick, String userSenha, String userTipo, String crmvMatricula) {
        this.id = id;
        this.pessoa = pessoa;
        this.userNick = userNick;
        this.userSenha = userSenha;
        this.userTipo = userTipo;
        this.crmvMatricula = crmvMatricula;
    }
    public User(UserId id, Pessoa pessoa, String userNick, String userSenha, String userTipo, String crmvMatricula, Set<Consulta> consultas) {
       this.id = id;
       this.pessoa = pessoa;
       this.userNick = userNick;
       this.userSenha = userSenha;
       this.userTipo = userTipo;
       this.crmvMatricula = crmvMatricula;
       this.consultas = consultas;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pkUser", column=@Column(name="PK_user", nullable=false) ), 
        @AttributeOverride(name="fkPessoa", column=@Column(name="FK_pessoa", nullable=false) ) } )
    public UserId getId() {
        return this.id;
    }
    
    public void setId(UserId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FK_pessoa", nullable=false, insertable=false, updatable=false)
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    
    @Column(name="userNick", nullable=false, length=100)
    public String getUserNick() {
        return this.userNick;
    }
    
    public void setUserNick(String userNick) {
        this.userNick = userNick;
    }

    
    @Column(name="userSenha", nullable=false, length=100)
    public String getUserSenha() {
        return this.userSenha;
    }
    
    public void setUserSenha(String userSenha) {
        this.userSenha = userSenha;
    }

    
    @Column(name="userTipo", nullable=false, length=20)
    public String getUserTipo() {
        return this.userTipo;
    }
    
    public void setUserTipo(String userTipo) {
        this.userTipo = userTipo;
    }

    
    @Column(name="crmvMatricula", unique=true, nullable=false, length=50)
    public String getCrmvMatricula() {
        return this.crmvMatricula;
    }
    
    public void setCrmvMatricula(String crmvMatricula) {
        this.crmvMatricula = crmvMatricula;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Consulta> getConsultas() {
        return this.consultas;
    }
    
    public void setConsultas(Set<Consulta> consultas) {
        this.consultas = consultas;
    }




}


