package com.lades.sihv.model;
// Generated 25/09/2018 14:47:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="bd_sihv"
    , uniqueConstraints = @UniqueConstraint(columnNames="registrationNumber") 
)
public class Users  implements java.io.Serializable {


     private Integer pkUser;
     private People people;
     private String userName;
     private String password;
     private String userProfile;
     private String registrationNumber;
     private Set powersHasUserses = new HashSet(0);
     private Set vetConsultations = new HashSet(0);
     private Set logBookHasUserses = new HashSet(0);

    public Users() {
    }

	
    public Users(People people, String userName, String password, String userProfile, String registrationNumber) {
        this.people = people;
        this.userName = userName;
        this.password = password;
        this.userProfile = userProfile;
        this.registrationNumber = registrationNumber;
    }
    public Users(People people, String userName, String password, String userProfile, String registrationNumber, Set powersHasUserses, Set vetConsultations, Set logBookHasUserses) {
       this.people = people;
       this.userName = userName;
       this.password = password;
       this.userProfile = userProfile;
       this.registrationNumber = registrationNumber;
       this.powersHasUserses = powersHasUserses;
       this.vetConsultations = vetConsultations;
       this.logBookHasUserses = logBookHasUserses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_user", unique=true, nullable=false)
    public Integer getPkUser() {
        return this.pkUser;
    }
    
    public void setPkUser(Integer pkUser) {
        this.pkUser = pkUser;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="people_PK_people", nullable=false)
    public People getPeople() {
        return this.people;
    }
    
    public void setPeople(People people) {
        this.people = people;
    }

    
    @Column(name="userName", nullable=false, length=100)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="password", nullable=false, length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="userProfile", nullable=false, length=34)
    public String getUserProfile() {
        return this.userProfile;
    }
    
    public void setUserProfile(String userProfile) {
        this.userProfile = userProfile;
    }

    
    @Column(name="registrationNumber", unique=true, nullable=false, length=50)
    public String getRegistrationNumber() {
        return this.registrationNumber;
    }
    
    public void setRegistrationNumber(String registrationNumber) {
        this.registrationNumber = registrationNumber;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set getPowersHasUserses() {
        return this.powersHasUserses;
    }
    
    public void setPowersHasUserses(Set powersHasUserses) {
        this.powersHasUserses = powersHasUserses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set getVetConsultations() {
        return this.vetConsultations;
    }
    
    public void setVetConsultations(Set vetConsultations) {
        this.vetConsultations = vetConsultations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set getLogBookHasUserses() {
        return this.logBookHasUserses;
    }
    
    public void setLogBookHasUserses(Set logBookHasUserses) {
        this.logBookHasUserses = logBookHasUserses;
    }




}


