package com.lades.sihv.model;
// Generated 08/11/2016 12:03:42 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserId generated by hbm2java
 */
@Embeddable
public class UserId  implements java.io.Serializable {


     private int pkUser;
     private int fkPessoa;

    public UserId() {
    }

    public UserId(int pkUser, int fkPessoa) {
       this.pkUser = pkUser;
       this.fkPessoa = fkPessoa;
    }
   


    @Column(name="PK_user", nullable=false)
    public int getPkUser() {
        return this.pkUser;
    }
    
    public void setPkUser(int pkUser) {
        this.pkUser = pkUser;
    }


    @Column(name="FK_pessoa", nullable=false)
    public int getFkPessoa() {
        return this.fkPessoa;
    }
    
    public void setFkPessoa(int fkPessoa) {
        this.fkPessoa = fkPessoa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserId) ) return false;
		 UserId castOther = ( UserId ) other; 
         
		 return (this.getPkUser()==castOther.getPkUser())
 && (this.getFkPessoa()==castOther.getFkPessoa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkUser();
         result = 37 * result + this.getFkPessoa();
         return result;
   }   


}


