-- MySQL Script generated by MySQL Workbench
-- Sex 29 Jul 2016 15:12:13 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BD_SIHV
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BD_SIHV
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_SIHV` ;
USE `BD_SIHV` ;

-- -----------------------------------------------------
-- Table `BD_SIHV`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIHV`.`pessoa` (
  `PK_pessoa` INT NOT NULL AUTO_INCREMENT,
  `CPF` BIGINT(11) NOT NULL,
  `RG` INT(7) NOT NULL,
  `NOME` VARCHAR(100) NOT NULL,
  `SEXO` SET('M', 'F') NOT NULL,
  `LOGRA` VARCHAR(100) NOT NULL,
  `CASA_NUMERO` VARCHAR(7) NOT NULL,
  `BAIRRO` VARCHAR(100) NOT NULL,
  `CIDADE` VARCHAR(100) NOT NULL,
  `CEP` INT(8) NOT NULL,
  `COMPLEMENTO` VARCHAR(100) NULL,
  `UF` SET('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RN', 'RS', 'RJ', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO') NOT NULL,
  `exclusaoLogica` TINYINT(1) NULL,
  `CAD_DATA_HORA` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`PK_pessoa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `BD_SIHV`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIHV`.`telefone` (
  `PK_telefone` INT NOT NULL AUTO_INCREMENT,
  `pessoa_PK_pessoa` INT NOT NULL,
  `numero` BIGINT(11) NOT NULL,
  PRIMARY KEY (`PK_telefone`),
  INDEX `fk_telefone_pessoa_idx` (`pessoa_PK_pessoa` ASC),
  CONSTRAINT `fk_telefone_pessoa`
    FOREIGN KEY (`pessoa_PK_pessoa`)
    REFERENCES `BD_SIHV`.`pessoa` (`PK_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
