-- MySQL Script generated by MySQL Workbench
-- 11/09/16 10:14:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_sihv
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_sihv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_sihv` ;
USE `bd_sihv` ;

-- -----------------------------------------------------
-- Table `bd_sihv`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sihv`.`pessoa` (
  `PK_pessoa` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(18) NOT NULL,
  `rg` INT(7) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `sexo` SET('M', 'F') NOT NULL,
  `logra` VARCHAR(100) NOT NULL,
  `casaNumero` VARCHAR(7) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `cep` INT(8) NOT NULL,
  `complemento` VARCHAR(100) NULL,
  `uf` SET('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RN', 'RS', 'RJ', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO') NOT NULL,
  `cadDataHora` TIMESTAMP(6) NOT NULL,
  `exclusaoLogica` TINYINT(1) NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`PK_pessoa`),
  UNIQUE INDEX `CPF_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_sihv`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sihv`.`cliente` (
  `PK_cliente` INT NOT NULL AUTO_INCREMENT,
  `FK_pessoa` INT NOT NULL,
  PRIMARY KEY (`PK_cliente`, `FK_pessoa`),
  INDEX `fk_cliente_pessoa1_idx` (`FK_pessoa` ASC),
  CONSTRAINT `fk_cliente_pessoa1`
    FOREIGN KEY (`FK_pessoa`)
    REFERENCES `bd_sihv`.`pessoa` (`PK_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sihv`.`animais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sihv`.`animais` (
  `PK_animal` INT NOT NULL AUTO_INCREMENT,
  `especie` VARCHAR(100) NOT NULL,
  `nomeAnimal` VARCHAR(70) NOT NULL,
  `raca` VARCHAR(100) NOT NULL,
  `pelagem` VARCHAR(100) NOT NULL,
  `sexoAnimal` SET('M', 'F') NOT NULL,
  `idadeAtual` INT(3) NOT NULL,
  `peso` DOUBLE NOT NULL,
  `cadDataHora` TIMESTAMP(6) NOT NULL,
  `cliente_FK_cliente` INT NOT NULL,
  `cliente_FK_pessoa` INT NOT NULL,
  PRIMARY KEY (`PK_animal`, `cliente_FK_cliente`, `cliente_FK_pessoa`),
  INDEX `fk_animais_cliente1_idx` (`cliente_FK_cliente` ASC, `cliente_FK_pessoa` ASC),
  CONSTRAINT `fk_animais_cliente1`
    FOREIGN KEY (`cliente_FK_cliente` , `cliente_FK_pessoa`)
    REFERENCES `bd_sihv`.`cliente` (`PK_cliente` , `FK_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_sihv`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sihv`.`telefone` (
  `PK_telefone` INT NOT NULL AUTO_INCREMENT,
  `FK_pessoa` INT NOT NULL,
  `numero` BIGINT(11) NOT NULL,
  PRIMARY KEY (`PK_telefone`),
  INDEX `fk_telefone_pessoa_idx` (`FK_pessoa` ASC),
  CONSTRAINT `fk_telefone_pessoa`
    FOREIGN KEY (`FK_pessoa`)
    REFERENCES `bd_sihv`.`pessoa` (`PK_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sihv`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sihv`.`user` (
  `PK_user` INT NOT NULL AUTO_INCREMENT,
  `FK_pessoa` INT NOT NULL,
  `userNick` VARCHAR(100) NOT NULL,
  `userSenha` VARCHAR(100) NOT NULL,
  `userTipo` SET('ALUNO', 'MEDICO', 'TÉCNICO') NOT NULL,
  `crmvMatricula` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`PK_user`, `FK_pessoa`),
  INDEX `fk_adm_pessoa1_idx` (`FK_pessoa` ASC),
  UNIQUE INDEX `CRMV_MATRICULA_UNIQUE` (`crmvMatricula` ASC),
  CONSTRAINT `fk_adm_pessoa1`
    FOREIGN KEY (`FK_pessoa`)
    REFERENCES `bd_sihv`.`pessoa` (`PK_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sihv`.`pelagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sihv`.`pelagem` (
  `PK_pelagem` INT NOT NULL AUTO_INCREMENT,
  `nomePelagem` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`PK_pelagem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sihv`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sihv`.`consulta` (
  `PK_consulta` INT NOT NULL AUTO_INCREMENT,
  `dataConsulta` TIMESTAMP(6) NOT NULL,
  `sistemasAfetados` VARCHAR(500) NULL,
  `animais_FK_animal` INT NOT NULL,
  `animais_cliente_FK_cliente` INT NOT NULL,
  `animais_cliente_FK_pessoa` INT NOT NULL,
  `user_FK_user` INT NOT NULL,
  `user_FK_pessoa` INT NOT NULL,
  PRIMARY KEY (`PK_consulta`),
  INDEX `fk_consulta_animais1_idx` (`animais_FK_animal` ASC, `animais_cliente_FK_cliente` ASC, `animais_cliente_FK_pessoa` ASC),
  INDEX `fk_consulta_user1_idx` (`user_FK_user` ASC, `user_FK_pessoa` ASC),
  CONSTRAINT `fk_consulta_animais1`
    FOREIGN KEY (`animais_FK_animal` , `animais_cliente_FK_cliente` , `animais_cliente_FK_pessoa`)
    REFERENCES `bd_sihv`.`animais` (`PK_animal` , `cliente_FK_cliente` , `cliente_FK_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_user1`
    FOREIGN KEY (`user_FK_user` , `user_FK_pessoa`)
    REFERENCES `bd_sihv`.`user` (`PK_user` , `FK_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sihv`.`anamnese`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sihv`.`anamnese` (
  `PK_anamnese` INT NOT NULL AUTO_INCREMENT,
  `queixaPrincipal` VARCHAR(300) NOT NULL,
  `jaFoiTratado` VARCHAR(3) NOT NULL,
  `medicacaoDose` VARCHAR(200) NULL,
  `antecMorbido` VARCHAR(200) NOT NULL,
  `histoFamiliar` VARCHAR(200) NOT NULL,
  `alimentacaoCaseira` VARCHAR(3) NOT NULL,
  `descriCaseira` VARCHAR(200) NULL,
  `alimentacaoRacao` VARCHAR(3) NOT NULL,
  `descriRacao` VARCHAR(200) NULL,
  `vacinacao` VARCHAR(22) NOT NULL,
  `sobreVacina` VARCHAR(100) NULL,
  `origemVacina` SET('NACIONAL', 'IMPORTADA') NULL,
  `vermifugacao` VARCHAR(3) NOT NULL,
  `doseVermifugacao` VARCHAR(50) NULL,
  `dataVermifugacao` DATE NULL,
  `ectoparasitas` VARCHAR(3) NOT NULL,
  `qualEctoparasitas` VARCHAR(34) NULL,
  `controEctoparasitas` VARCHAR(3) NULL,
  `qualProdutoUtiliza` VARCHAR(50) NULL,
  `acessoRua` VARCHAR(24) NOT NULL,
  `descriHabitat` VARCHAR(200) NULL,
  `contactantes` VARCHAR(3) NULL,
  `descriContactantes` VARCHAR(200) NULL,
  `mesmoProbleContacta` VARCHAR(3) NULL,
  `contatoRoedor` VARCHAR(3) NULL,
  `consulta_FK_consulta` INT NOT NULL,
  PRIMARY KEY (`PK_anamnese`, `consulta_FK_consulta`),
  INDEX `fk_anamnese_consulta1_idx` (`consulta_FK_consulta` ASC),
  CONSTRAINT `fk_anamnese_consulta1`
    FOREIGN KEY (`consulta_FK_consulta`)
    REFERENCES `bd_sihv`.`consulta` (`PK_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sihv`.`sisDigestorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sihv`.`sisDigestorio` (
  `PK_sisDigestorio` INT NOT NULL AUTO_INCREMENT,
  `estaSeAlimentando` VARCHAR(3) NOT NULL,
  `descriNaoSeAlimeta` VARCHAR(200) NULL,
  `vomito` VARCHAR(3) NOT NULL,
  `aspectoVomito` VARCHAR(100) NULL,
  `evoluVomito` VARCHAR(200) NULL,
  `regurgitacao` VARCHAR(3) NOT NULL,
  `evoluRegurgitacao` VARCHAR(200) NULL,
  `diarreia` VARCHAR(3) NOT NULL,
  `aspectDiarreia` VARCHAR(100) NULL,
  `evoluDiarreia` VARCHAR(100) NULL,
  `disquesiaTenesmo` VARCHAR(3) NOT NULL,
  `evoluDisquesiaTenesmo` VARCHAR(100) NULL,
  `sistemaAfetado` SET('SIM', 'NÃO') NOT NULL,
  `consulta_FK_consulta` INT NOT NULL,
  PRIMARY KEY (`PK_sisDigestorio`, `consulta_FK_consulta`),
  INDEX `fk_sis_digestorio_consulta1_idx` (`consulta_FK_consulta` ASC),
  CONSTRAINT `fk_sis_digestorio_consulta1`
    FOREIGN KEY (`consulta_FK_consulta`)
    REFERENCES `bd_sihv`.`consulta` (`PK_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sihv`.`sisRespCardio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sihv`.`sisRespCardio` (
  `PK_sisRespCardio` INT NOT NULL AUTO_INCREMENT,
  `tosse` VARCHAR(3) NOT NULL,
  `tosseProdutiva` SET('PRODUTIVA', 'NÃO PRODUTIVA') NULL,
  `tosseEvolu` VARCHAR(200) NULL,
  `espirro` VARCHAR(3) NOT NULL,
  `espirroEvolu` VARCHAR(200) NULL,
  `secrecaoNasal` VARCHAR(3) NOT NULL,
  `secreNasalUniBilateral` SET('UNILATERAL', 'BILATERAL') NULL,
  `secreNasalTipo` VARCHAR(50) NULL,
  `secreNasalEvolu` VARCHAR(200) NULL,
  `dispneiaTaquipneia` VARCHAR(3) NOT NULL,
  `dispnTaquipEvolu` VARCHAR(200) NULL,
  `cianose` VARCHAR(3) NOT NULL,
  `quandApreseCianose` DATE NULL,
  `cianoseEvolu` VARCHAR(200) NULL,
  `cansacoFacil` VARCHAR(3) NOT NULL,
  `cansaFacilEvolu` VARCHAR(200) NULL,
  `sincope` VARCHAR(3) NOT NULL,
  `sincopeEvolu` VARCHAR(200) NULL,
  `emagrecimento` VARCHAR(3) NOT NULL,
  `emagrecEvolu` VARCHAR(200) NULL,
  `sistemaAfetado` SET('SIM', 'NÃO') NOT NULL,
  `consulta_FK_consulta` INT NOT NULL,
  PRIMARY KEY (`PK_sisRespCardio`, `consulta_FK_consulta`),
  INDEX `fk_Sis_Resp_Cardio_consulta1_idx` (`consulta_FK_consulta` ASC),
  CONSTRAINT `fk_Sis_Resp_Cardio_consulta1`
    FOREIGN KEY (`consulta_FK_consulta`)
    REFERENCES `bd_sihv`.`consulta` (`PK_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sihv`.`sisUrinarioMamaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sihv`.`sisUrinarioMamaria` (
  `PK_sisUrinarioMamaria` INT NOT NULL AUTO_INCREMENT,
  `ingestHidrica` VARCHAR(10) NOT NULL,
  `ingestHidricaEvolu` VARCHAR(200) NULL,
  `estadoUrina` VARCHAR(8) NOT NULL,
  `urina` VARCHAR(13) NOT NULL,
  `urinaAspecto` VARCHAR(200) NULL,
  `urinaEvolu` VARCHAR(200) NULL,
  `ultimoCio` DATE NOT NULL,
  `ultimoParto` DATE NOT NULL,
  `secreVagiPeni` VARCHAR(3) NOT NULL,
  `secreVagiPeniTipo` VARCHAR(50) NULL,
  `secreVagiPeniEvolu` VARCHAR(200) NULL,
  `castrado` VARCHAR(3) NOT NULL,
  `prenhe` VARCHAR(3) NOT NULL,
  `sistemaAfetado` SET('SIM', 'NÃO') NOT NULL,
  `consulta_FK_consulta` INT NOT NULL,
  PRIMARY KEY (`PK_sisUrinarioMamaria`, `consulta_FK_consulta`),
  CONSTRAINT `fk_Sis_Urinario_Mamaria_consulta1`
    FOREIGN KEY (`consulta_FK_consulta`)
    REFERENCES `bd_sihv`.`consulta` (`PK_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sihv`.`sisTegumentar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sihv`.`sisTegumentar` (
  `PK_sisTegumentar` INT NOT NULL AUTO_INCREMENT,
  `evoluLesao` VARCHAR(200) NOT NULL,
  `localiLesao` VARCHAR(200) NOT NULL,
  `pruridoCutaneo` VARCHAR(3) NOT NULL,
  `pruridoCutaneoEvolu` VARCHAR(50) NULL,
  `pruridoOtolog` VARCHAR(3) NOT NULL,
  `pruridoOtologEvolu` VARCHAR(50) NULL,
  `secreOtolog` VARCHAR(3) NOT NULL,
  `secreOtologEvolu` VARCHAR(50) NULL,
  `frequeBanhos` VARCHAR(50) NOT NULL,
  `produUtilBanho` VARCHAR(50) NULL,
  `sistemaAfetado` SET('SIM', 'NÃO') NOT NULL,
  `consulta_FK_consulta` INT NOT NULL,
  PRIMARY KEY (`PK_sisTegumentar`, `consulta_FK_consulta`),
  INDEX `fk_Sis_Tegumentar_consulta1_idx` (`consulta_FK_consulta` ASC),
  CONSTRAINT `fk_Sis_Tegumentar_consulta1`
    FOREIGN KEY (`consulta_FK_consulta`)
    REFERENCES `bd_sihv`.`consulta` (`PK_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sihv`.`sisNeurologico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sihv`.`sisNeurologico` (
  `PK_sisNeurologico` INT NOT NULL AUTO_INCREMENT,
  `consciencia` VARCHAR(9) NOT NULL,
  `comportamento` VARCHAR(13) NOT NULL,
  `ataxia` VARCHAR(3) NOT NULL,
  `ataxiaTipo` VARCHAR(50) NULL,
  `ataxiaEvolu` VARCHAR(200) NULL,
  `paralisia` VARCHAR(3) NOT NULL,
  `paralisiaEspFla` VARCHAR(9) NULL,
  `paralisiaTipo` VARCHAR(50) NULL,
  `paralisiaEvolu` VARCHAR(200) NULL,
  `convulsao` VARCHAR(3) NOT NULL,
  `convulsaoTipo` VARCHAR(50) NULL,
  `convulsaoEvolu` VARCHAR(200) NULL,
  `audicao` VARCHAR(6) NOT NULL,
  `sistemaAfetado` SET('SIM', 'NÃO') NOT NULL,
  `consulta_FK_consulta` INT NOT NULL,
  PRIMARY KEY (`PK_sisNeurologico`, `consulta_FK_consulta`),
  INDEX `fk_Sis_Neurologico_consulta1_idx` (`consulta_FK_consulta` ASC),
  CONSTRAINT `fk_Sis_Neurologico_consulta1`
    FOREIGN KEY (`consulta_FK_consulta`)
    REFERENCES `bd_sihv`.`consulta` (`PK_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sihv`.`sisOftalmico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sihv`.`sisOftalmico` (
  `PK_sisOftalmico` INT NOT NULL AUTO_INCREMENT,
  `olhos` VARCHAR(10) NOT NULL,
  `secreOcular` VARCHAR(3) NOT NULL,
  `secreOcularUniBi` VARCHAR(10) NULL,
  `secreOculaTipo` VARCHAR(50) NULL,
  `secreOculaEvolu` VARCHAR(200) NULL,
  `blefaroespasmo` VARCHAR(3) NOT NULL,
  `blefaroComenta` VARCHAR(50) NULL,
  `exoftalmia` VARCHAR(3) NOT NULL,
  `exoftalComenra` VARCHAR(50) NULL,
  `sistemaAfetado` SET('SIM', 'NÃO') NOT NULL,
  `consulta_FK_consulta` INT NOT NULL,
  PRIMARY KEY (`PK_sisOftalmico`, `consulta_FK_consulta`),
  INDEX `fk_Sis_Oftalmico_consulta1_idx` (`consulta_FK_consulta` ASC),
  CONSTRAINT `fk_Sis_Oftalmico_consulta1`
    FOREIGN KEY (`consulta_FK_consulta`)
    REFERENCES `bd_sihv`.`consulta` (`PK_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sihv`.`sisMuscEsque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sihv`.`sisMuscEsque` (
  `PK_sisMuscEsque` INT NOT NULL AUTO_INCREMENT,
  `claudicacao` VARCHAR(3) NOT NULL,
  `claudicacaoEvolu` VARCHAR(50) NULL,
  `fraturas` VARCHAR(3) NOT NULL,
  `fraturasEvolu` VARCHAR(50) NULL,
  `atrofMusc` VARCHAR(3) NOT NULL,
  `atrofMuscEvolu` VARCHAR(50) NULL,
  `sistemaAfetado` SET('SIM', 'NÃO') NOT NULL,
  `consulta_FK_consulta` INT NOT NULL,
  PRIMARY KEY (`PK_sisMuscEsque`, `consulta_FK_consulta`),
  INDEX `fk_Sis_MuscEsque_consulta1_idx` (`consulta_FK_consulta` ASC),
  CONSTRAINT `fk_Sis_MuscEsque_consulta1`
    FOREIGN KEY (`consulta_FK_consulta`)
    REFERENCES `bd_sihv`.`consulta` (`PK_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sihv`.`exameFisico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sihv`.`exameFisico` (
  `PK_exameFisico` INT NOT NULL AUTO_INCREMENT,
  `fcBpm` DOUBLE NOT NULL,
  `frMpm` DOUBLE NOT NULL,
  `termpeReta` DOUBLE NOT NULL,
  `tpc` DOUBLE NOT NULL,
  `estadoNutric` VARCHAR(9) NOT NULL,
  `mucosaOral` VARCHAR(10) NOT NULL,
  `mucosVagPeni` VARCHAR(10) NOT NULL,
  `mucosaOcular` VARCHAR(10) NOT NULL,
  `pulso` VARCHAR(7) NOT NULL,
  `estadoPulso` VARCHAR(9) NOT NULL,
  `hidratacao` VARCHAR(22) NOT NULL,
  `palpaAbdom` VARCHAR(200) NOT NULL,
  `auscuCardiaca` VARCHAR(200) NOT NULL,
  `auscuPulmona` VARCHAR(200) NOT NULL,
  `linfonodos` VARCHAR(200) NOT NULL,
  `pelePelos` VARCHAR(200) NOT NULL,
  `diagDiferenciais` INT NOT NULL,
  `consulta_FK_consulta` INT NOT NULL,
  PRIMARY KEY (`PK_exameFisico`, `consulta_FK_consulta`),
  INDEX `fk_ExameFisico_consulta1_idx` (`consulta_FK_consulta` ASC),
  CONSTRAINT `fk_ExameFisico_consulta1`
    FOREIGN KEY (`consulta_FK_consulta`)
    REFERENCES `bd_sihv`.`consulta` (`PK_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sihv`.`exameImage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sihv`.`exameImage` (
  `PK_exameImage` INT NOT NULL AUTO_INCREMENT,
  `regiExami` VARCHAR(200) NOT NULL,
  `posicao` VARCHAR(50) NULL,
  `qtdChapas` INT NULL,
  `laudo` VARCHAR(200) NULL,
  `tipo` SET('RAIOX', 'ULTRASSOM') NULL,
  `dataExaImage` TIMESTAMP(6) NULL,
  `consulta_FK_consulta` INT NOT NULL,
  PRIMARY KEY (`PK_exameImage`, `consulta_FK_consulta`),
  INDEX `fk_ExameImage_consulta1_idx` (`consulta_FK_consulta` ASC),
  CONSTRAINT `fk_ExameImage_consulta1`
    FOREIGN KEY (`consulta_FK_consulta`)
    REFERENCES `bd_sihv`.`consulta` (`PK_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
