-- MySQL Script generated by MySQL Workbench
-- Qui 27 Out 2016 12:00:39 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BD_SIHV
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BD_SIHV
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_SIHV` ;
USE `BD_SIHV` ;

-- -----------------------------------------------------
-- Table `BD_SIHV`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIHV`.`pessoa` (
  `PK_pessoa` INT NOT NULL AUTO_INCREMENT,
  `CPF` BIGINT(11) NOT NULL,
  `RG` INT(7) NOT NULL,
  `NOME` VARCHAR(100) NOT NULL,
  `SEXO` SET('M', 'F') NOT NULL,
  `LOGRA` VARCHAR(100) NOT NULL,
  `CASA_NUMERO` VARCHAR(7) NOT NULL,
  `BAIRRO` VARCHAR(100) NOT NULL,
  `CIDADE` VARCHAR(100) NOT NULL,
  `CEP` INT(8) NOT NULL,
  `COMPLEMENTO` VARCHAR(100) NULL,
  `UF` SET('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RN', 'RS', 'RJ', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO') NOT NULL,
  `CAD_DATA_HORA` TIMESTAMP(6) NOT NULL,
  `exclusaoLogica` TINYINT(1) NULL,
  PRIMARY KEY (`PK_pessoa`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `BD_SIHV`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIHV`.`cliente` (
  `PK_cliente` INT NOT NULL AUTO_INCREMENT,
  `FK_pessoa` INT NOT NULL,
  PRIMARY KEY (`PK_cliente`, `FK_pessoa`),
  INDEX `fk_cliente_pessoa1_idx` (`FK_pessoa` ASC),
  CONSTRAINT `fk_cliente_pessoa1`
    FOREIGN KEY (`FK_pessoa`)
    REFERENCES `BD_SIHV`.`pessoa` (`PK_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIHV`.`animais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIHV`.`animais` (
  `PK_animal` INT NOT NULL AUTO_INCREMENT,
  `ESPECIE` VARCHAR(100) NOT NULL,
  `NOME` VARCHAR(70) NOT NULL,
  `RACA` VARCHAR(100) NOT NULL,
  `PELAGEM` VARCHAR(100) NOT NULL,
  `SEXO` SET('M', 'F') NOT NULL,
  `IDADE_ATUAL` INT(3) NOT NULL,
  `PESO` DOUBLE NOT NULL,
  `CAD_DATA_HORA` TIMESTAMP(6) NOT NULL,
  `cliente_FK_cliente` INT NOT NULL,
  `cliente_FK_pessoa` INT NOT NULL,
  PRIMARY KEY (`PK_animal`, `cliente_FK_cliente`, `cliente_FK_pessoa`),
  INDEX `fk_animais_cliente1_idx` (`cliente_FK_cliente` ASC, `cliente_FK_pessoa` ASC),
  CONSTRAINT `fk_animais_cliente1`
    FOREIGN KEY (`cliente_FK_cliente` , `cliente_FK_pessoa`)
    REFERENCES `BD_SIHV`.`cliente` (`PK_cliente` , `FK_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `BD_SIHV`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIHV`.`telefone` (
  `PK_telefone` INT NOT NULL AUTO_INCREMENT,
  `pessoa_PK_pessoa` INT NOT NULL,
  `numero` BIGINT(11) NOT NULL,
  PRIMARY KEY (`PK_telefone`),
  INDEX `fk_telefone_pessoa_idx` (`pessoa_PK_pessoa` ASC),
  CONSTRAINT `fk_telefone_pessoa`
    FOREIGN KEY (`pessoa_PK_pessoa`)
    REFERENCES `BD_SIHV`.`pessoa` (`PK_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIHV`.`adm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIHV`.`adm` (
  `PK_adm` INT NOT NULL AUTO_INCREMENT,
  `FK_pessoa` INT NOT NULL,
  `adm_senha` VARCHAR(100) NOT NULL,
  `adm_login` VARCHAR(100) NOT NULL,
  `TIPO_USER` SET('Aluno', 'Medico', 'Tecnico ') NOT NULL,
  `CRMV_MATRICULA` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`PK_adm`, `FK_pessoa`),
  INDEX `fk_adm_pessoa1_idx` (`FK_pessoa` ASC),
  UNIQUE INDEX `CRMV_MATRICULA_UNIQUE` (`CRMV_MATRICULA` ASC),
  CONSTRAINT `fk_adm_pessoa1`
    FOREIGN KEY (`FK_pessoa`)
    REFERENCES `BD_SIHV`.`pessoa` (`PK_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIHV`.`pelagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIHV`.`pelagem` (
  `PK_pelagem` INT NOT NULL AUTO_INCREMENT,
  `nomePelagem` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`PK_pelagem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIHV`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIHV`.`consulta` (
  `PK_consulta` INT NOT NULL AUTO_INCREMENT,
  `DataConsulta` TIMESTAMP(6) NOT NULL,
  `SistemasAfetados` VARCHAR(500) NULL,
  `adm_PK_adm` INT NOT NULL,
  `adm_FK_pessoa` INT NOT NULL,
  `animais_PK_animal` INT NOT NULL,
  `animais_cliente_FK_cliente` INT NOT NULL,
  `animais_cliente_FK_pessoa` INT NOT NULL,
  PRIMARY KEY (`PK_consulta`),
  INDEX `fk_consulta_adm1_idx` (`adm_PK_adm` ASC, `adm_FK_pessoa` ASC),
  INDEX `fk_consulta_animais1_idx` (`animais_PK_animal` ASC, `animais_cliente_FK_cliente` ASC, `animais_cliente_FK_pessoa` ASC),
  CONSTRAINT `fk_consulta_adm1`
    FOREIGN KEY (`adm_PK_adm` , `adm_FK_pessoa`)
    REFERENCES `BD_SIHV`.`adm` (`PK_adm` , `FK_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_animais1`
    FOREIGN KEY (`animais_PK_animal` , `animais_cliente_FK_cliente` , `animais_cliente_FK_pessoa`)
    REFERENCES `BD_SIHV`.`animais` (`PK_animal` , `cliente_FK_cliente` , `cliente_FK_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIHV`.`anamnese`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIHV`.`anamnese` (
  `PK_ANAMNESE` INT NOT NULL AUTO_INCREMENT,
  `QueixaPrincipal` VARCHAR(300) NOT NULL,
  `JaFoiTratado` VARCHAR(3) NOT NULL,
  `MedicacaoDose` VARCHAR(200) NULL,
  `AntecMorbido` VARCHAR(200) NOT NULL,
  `HistoFamiliar` VARCHAR(200) NOT NULL,
  `AlimentacaoCaseira` VARCHAR(3) NOT NULL,
  `DescriCaseira` VARCHAR(200) NULL,
  `AlimentacaoRacao` VARCHAR(3) NOT NULL,
  `DescriRacao` VARCHAR(200) NULL,
  `Vacinacao` VARCHAR(22) NOT NULL,
  `SobreVacina` VARCHAR(100) NULL,
  `OrigemVacina` SET('Nacional', 'Importada') NULL,
  `Vermifugacao` VARCHAR(3) NOT NULL,
  `DoseVermifugacao` VARCHAR(50) NULL,
  `DataVermifugacao` DATE NULL,
  `Ectoparasitas` VARCHAR(3) NOT NULL,
  `QualEctoparasitas` VARCHAR(34) NULL,
  `ControEctoparasitas` VARCHAR(3) NULL,
  `QualProdutoUtiliza` VARCHAR(50) NULL,
  `AcessoRua` VARCHAR(24) NOT NULL,
  `DescriHabitat` VARCHAR(200) NULL,
  `Contactantes` VARCHAR(3) NULL,
  `DescriContactantes` VARCHAR(200) NULL,
  `MesmoProbleContacta` VARCHAR(3) NULL,
  `ContatoRoedor` VARCHAR(3) NULL,
  `consulta_PK_consulta` INT NOT NULL,
  PRIMARY KEY (`PK_ANAMNESE`, `consulta_PK_consulta`),
  INDEX `fk_anamnese_consulta1_idx` (`consulta_PK_consulta` ASC),
  CONSTRAINT `fk_anamnese_consulta1`
    FOREIGN KEY (`consulta_PK_consulta`)
    REFERENCES `BD_SIHV`.`consulta` (`PK_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIHV`.`sis_digestorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIHV`.`sis_digestorio` (
  `PK_sis_digestorio` INT NOT NULL AUTO_INCREMENT,
  `EstaSeAlimentando` VARCHAR(3) NOT NULL,
  `DescriNaoSeAlimeta` VARCHAR(200) NULL,
  `Vomito` VARCHAR(3) NOT NULL,
  `AspectoVomito` VARCHAR(100) NULL,
  `EvoluVomito` VARCHAR(200) NULL,
  `Regurgitacao` VARCHAR(3) NOT NULL,
  `EvoluRegurgitacao` VARCHAR(200) NULL,
  `Diarreia` VARCHAR(3) NOT NULL,
  `AspectDiarreia` VARCHAR(100) NULL,
  `EvoluDiarreia` VARCHAR(100) NULL,
  `DisquesiaTenesmo` VARCHAR(3) NOT NULL,
  `EvoluDisquesiaTenesmo` VARCHAR(100) NULL,
  `SistemaAfetado` SET('Sim', 'Não') NOT NULL,
  `consulta_PK_consulta` INT NOT NULL,
  PRIMARY KEY (`PK_sis_digestorio`, `consulta_PK_consulta`),
  INDEX `fk_sis_digestorio_consulta1_idx` (`consulta_PK_consulta` ASC),
  CONSTRAINT `fk_sis_digestorio_consulta1`
    FOREIGN KEY (`consulta_PK_consulta`)
    REFERENCES `BD_SIHV`.`consulta` (`PK_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIHV`.`Sis_Resp_Cardio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIHV`.`Sis_Resp_Cardio` (
  `PK_Sis_Resp_Cardio` INT NOT NULL AUTO_INCREMENT,
  `Tosse` VARCHAR(3) NOT NULL,
  `TosseProdutiva` SET('Produtiva', 'Não produtiva') NULL,
  `TosseEvolu` VARCHAR(200) NULL,
  `Espirro` VARCHAR(3) NOT NULL,
  `EspirroEvolu` VARCHAR(200) NULL,
  `SecrecaoNasal` VARCHAR(3) NOT NULL,
  `SecreNasalUniBilateral` SET('Unilateral', 'Bilateral') NULL,
  `SecreNasalTipo` VARCHAR(50) NULL,
  `SecreNasalEvolu` VARCHAR(200) NULL,
  `DispneiaTaquipneia` VARCHAR(3) NOT NULL,
  `DispnTaquipEvolu` VARCHAR(200) NULL,
  `Cianose` VARCHAR(3) NOT NULL,
  `QuandApreseCianose` DATE NULL,
  `CianoseEvolu` VARCHAR(200) NULL,
  `CansacoFacil` VARCHAR(3) NOT NULL,
  `CansaFacilEvolu` VARCHAR(200) NULL,
  `Sincope` VARCHAR(3) NOT NULL,
  `SincopeEvolu` VARCHAR(200) NULL,
  `Emagrecimento` VARCHAR(3) NOT NULL,
  `EmagrecEvolu` VARCHAR(200) NULL,
  `SistemaAfetado` SET('Sim', 'Não') NOT NULL,
  `consulta_PK_consulta` INT NOT NULL,
  PRIMARY KEY (`PK_Sis_Resp_Cardio`, `consulta_PK_consulta`),
  INDEX `fk_Sis_Resp_Cardio_consulta1_idx` (`consulta_PK_consulta` ASC),
  CONSTRAINT `fk_Sis_Resp_Cardio_consulta1`
    FOREIGN KEY (`consulta_PK_consulta`)
    REFERENCES `BD_SIHV`.`consulta` (`PK_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIHV`.`Sis_Urinario_Mamaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIHV`.`Sis_Urinario_Mamaria` (
  `PK_Sis_Urinario_Mamaria` INT NOT NULL AUTO_INCREMENT,
  `IngestHidrica` VARCHAR(10) NOT NULL,
  `IngestHidricaEvolu` VARCHAR(200) NULL,
  `EstadoUrina` VARCHAR(8) NOT NULL,
  `Urina` VARCHAR(13) NOT NULL,
  `UrinaAspecto` VARCHAR(200) NULL,
  `UrinaEvolu` VARCHAR(200) NULL,
  `UltimoCio` DATE NOT NULL,
  `UltimoParto` DATE NOT NULL,
  `SecreVagiPeni` VARCHAR(3) NOT NULL,
  `SecreVagiPeniTipo` VARCHAR(50) NULL,
  `SecreVagiPeniEvolu` VARCHAR(200) NULL,
  `Castrado` VARCHAR(3) NOT NULL,
  `Prenhe` VARCHAR(3) NOT NULL,
  `SistemaAfetado` SET('Sim', 'Não') NOT NULL,
  `consulta_PK_consulta` INT NOT NULL,
  PRIMARY KEY (`PK_Sis_Urinario_Mamaria`, `consulta_PK_consulta`),
  CONSTRAINT `fk_Sis_Urinario_Mamaria_consulta1`
    FOREIGN KEY (`consulta_PK_consulta`)
    REFERENCES `BD_SIHV`.`consulta` (`PK_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIHV`.`Sis_Tegumentar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIHV`.`Sis_Tegumentar` (
  `PK_Sis_Tegumentar` INT NOT NULL AUTO_INCREMENT,
  `EvoluLesao` VARCHAR(200) NOT NULL,
  `LocaliLesao` VARCHAR(200) NOT NULL,
  `PruridoCutaneo` VARCHAR(3) NOT NULL,
  `PruridoCutaneoEvolu` VARCHAR(50) NULL,
  `PruridoOtolog` VARCHAR(3) NOT NULL,
  `PruridoOtologEvolu` VARCHAR(50) NULL,
  `SecreOtolog` VARCHAR(3) NOT NULL,
  `SecreOtologEvolu` VARCHAR(50) NULL,
  `FrequeBanhos` VARCHAR(50) NOT NULL,
  `ProduUtilBanho` VARCHAR(50) NULL,
  `SistemaAfetado` SET('Sim', 'Não') NOT NULL,
  `consulta_PK_consulta` INT NOT NULL,
  PRIMARY KEY (`PK_Sis_Tegumentar`, `consulta_PK_consulta`),
  INDEX `fk_Sis_Tegumentar_consulta1_idx` (`consulta_PK_consulta` ASC),
  CONSTRAINT `fk_Sis_Tegumentar_consulta1`
    FOREIGN KEY (`consulta_PK_consulta`)
    REFERENCES `BD_SIHV`.`consulta` (`PK_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIHV`.`Sis_Neurologico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIHV`.`Sis_Neurologico` (
  `PK_Sis_Neurologico` INT NOT NULL AUTO_INCREMENT,
  `Consciencia` VARCHAR(9) NOT NULL,
  `Comportamento` VARCHAR(13) NOT NULL,
  `Ataxia` VARCHAR(3) NOT NULL,
  `AtaxiaTipo` VARCHAR(50) NULL,
  `AtaxiaEvolu` VARCHAR(200) NULL,
  `Paralisia` VARCHAR(3) NOT NULL,
  `ParalisiaEspFla` VARCHAR(9) NULL,
  `ParalisiaTipo` VARCHAR(50) NULL,
  `ParalisiaEvolu` VARCHAR(200) NULL,
  `Convulsao` VARCHAR(3) NOT NULL,
  `ConvulsaoTipo` VARCHAR(50) NULL,
  `ConvulsaoEvolu` VARCHAR(200) NULL,
  `Audicao` VARCHAR(6) NOT NULL,
  `SistemaAfetado` SET('Sim', 'Não') NOT NULL,
  `consulta_PK_consulta` INT NOT NULL,
  PRIMARY KEY (`PK_Sis_Neurologico`, `consulta_PK_consulta`),
  INDEX `fk_Sis_Neurologico_consulta1_idx` (`consulta_PK_consulta` ASC),
  CONSTRAINT `fk_Sis_Neurologico_consulta1`
    FOREIGN KEY (`consulta_PK_consulta`)
    REFERENCES `BD_SIHV`.`consulta` (`PK_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
