package Model;
// Generated 25/07/2016 11:36:44 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ExameFis generated by hbm2java
 */
public class ExameFis  implements java.io.Serializable {


     private Integer id;
     private Entrada entrada;
     private int fc;
     private int fr;
     private int TC;
     private int tpc;
     private String inspecGeral;
     private String estadoNutri;
     private String mucosas;
     private String pulso;
     private String hidrata;
     private String palpaAbd;
     private String aulsCardpul;
     private String linfonodos;
     private String pele;
     private String obs;
     private int idOpera;
     private Date data;

    public ExameFis() {
    }

	
    public ExameFis(Entrada entrada, int fc, int fr, int TC, int tpc, String inspecGeral, String estadoNutri, String mucosas, String pulso, String hidrata, String palpaAbd, String aulsCardpul, String linfonodos, String pele, String obs, int idOpera) {
        this.entrada = entrada;
        this.fc = fc;
        this.fr = fr;
        this.TC = TC;
        this.tpc = tpc;
        this.inspecGeral = inspecGeral;
        this.estadoNutri = estadoNutri;
        this.mucosas = mucosas;
        this.pulso = pulso;
        this.hidrata = hidrata;
        this.palpaAbd = palpaAbd;
        this.aulsCardpul = aulsCardpul;
        this.linfonodos = linfonodos;
        this.pele = pele;
        this.obs = obs;
        this.idOpera = idOpera;
    }
    public ExameFis(Entrada entrada, int fc, int fr, int TC, int tpc, String inspecGeral, String estadoNutri, String mucosas, String pulso, String hidrata, String palpaAbd, String aulsCardpul, String linfonodos, String pele, String obs, int idOpera, Date data) {
       this.entrada = entrada;
       this.fc = fc;
       this.fr = fr;
       this.TC = TC;
       this.tpc = tpc;
       this.inspecGeral = inspecGeral;
       this.estadoNutri = estadoNutri;
       this.mucosas = mucosas;
       this.pulso = pulso;
       this.hidrata = hidrata;
       this.palpaAbd = palpaAbd;
       this.aulsCardpul = aulsCardpul;
       this.linfonodos = linfonodos;
       this.pele = pele;
       this.obs = obs;
       this.idOpera = idOpera;
       this.data = data;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Entrada getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(Entrada entrada) {
        this.entrada = entrada;
    }
    public int getFc() {
        return this.fc;
    }
    
    public void setFc(int fc) {
        this.fc = fc;
    }
    public int getFr() {
        return this.fr;
    }
    
    public void setFr(int fr) {
        this.fr = fr;
    }
    public int getTC() {
        return this.TC;
    }
    
    public void setTC(int TC) {
        this.TC = TC;
    }
    public int getTpc() {
        return this.tpc;
    }
    
    public void setTpc(int tpc) {
        this.tpc = tpc;
    }
    public String getInspecGeral() {
        return this.inspecGeral;
    }
    
    public void setInspecGeral(String inspecGeral) {
        this.inspecGeral = inspecGeral;
    }
    public String getEstadoNutri() {
        return this.estadoNutri;
    }
    
    public void setEstadoNutri(String estadoNutri) {
        this.estadoNutri = estadoNutri;
    }
    public String getMucosas() {
        return this.mucosas;
    }
    
    public void setMucosas(String mucosas) {
        this.mucosas = mucosas;
    }
    public String getPulso() {
        return this.pulso;
    }
    
    public void setPulso(String pulso) {
        this.pulso = pulso;
    }
    public String getHidrata() {
        return this.hidrata;
    }
    
    public void setHidrata(String hidrata) {
        this.hidrata = hidrata;
    }
    public String getPalpaAbd() {
        return this.palpaAbd;
    }
    
    public void setPalpaAbd(String palpaAbd) {
        this.palpaAbd = palpaAbd;
    }
    public String getAulsCardpul() {
        return this.aulsCardpul;
    }
    
    public void setAulsCardpul(String aulsCardpul) {
        this.aulsCardpul = aulsCardpul;
    }
    public String getLinfonodos() {
        return this.linfonodos;
    }
    
    public void setLinfonodos(String linfonodos) {
        this.linfonodos = linfonodos;
    }
    public String getPele() {
        return this.pele;
    }
    
    public void setPele(String pele) {
        this.pele = pele;
    }
    public String getObs() {
        return this.obs;
    }
    
    public void setObs(String obs) {
        this.obs = obs;
    }
    public int getIdOpera() {
        return this.idOpera;
    }
    
    public void setIdOpera(int idOpera) {
        this.idOpera = idOpera;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }




}


