package MODELO;
// Generated 31/07/2016 22:50:27 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Adm generated by hbm2java
 */
@Entity
@Table(name="adm"
    ,catalog="BD_SIHV"
)
public class Adm  implements java.io.Serializable {


     private AdmId id;
     private Pessoa pessoa;
     private String admSenha;
     private String admLogin;

    public Adm() {
    }

    public Adm(AdmId id, Pessoa pessoa, String admSenha, String admLogin) {
       this.id = id;
       this.pessoa = pessoa;
       this.admSenha = admSenha;
       this.admLogin = admLogin;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pkAdm", column=@Column(name="PK_adm", nullable=false) ), 
        @AttributeOverride(name="fkPessoa", column=@Column(name="FK_pessoa", nullable=false) ) } )
    public AdmId getId() {
        return this.id;
    }
    
    public void setId(AdmId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FK_pessoa", nullable=false, insertable=false, updatable=false)
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    
    @Column(name="adm_senha", nullable=false, length=100)
    public String getAdmSenha() {
        return this.admSenha;
    }
    
    public void setAdmSenha(String admSenha) {
        this.admSenha = admSenha;
    }

    
    @Column(name="adm_login", nullable=false, length=100)
    public String getAdmLogin() {
        return this.admLogin;
    }
    
    public void setAdmLogin(String admLogin) {
        this.admLogin = admLogin;
    }




}


