package MODELO;
// Generated 21/10/2016 12:33:23 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AnamneseId generated by hbm2java
 */
@Embeddable
public class AnamneseId  implements java.io.Serializable {


     private int pkAnamnese;
     private int consultaPkConsulta;

    public AnamneseId() {
    }

    public AnamneseId(int pkAnamnese, int consultaPkConsulta) {
       this.pkAnamnese = pkAnamnese;
       this.consultaPkConsulta = consultaPkConsulta;
    }
   


    @Column(name="PK_ANAMNESE", nullable=false)
    public int getPkAnamnese() {
        return this.pkAnamnese;
    }
    
    public void setPkAnamnese(int pkAnamnese) {
        this.pkAnamnese = pkAnamnese;
    }


    @Column(name="consulta_PK_consulta", nullable=false)
    public int getConsultaPkConsulta() {
        return this.consultaPkConsulta;
    }
    
    public void setConsultaPkConsulta(int consultaPkConsulta) {
        this.consultaPkConsulta = consultaPkConsulta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AnamneseId) ) return false;
		 AnamneseId castOther = ( AnamneseId ) other; 
         
		 return (this.getPkAnamnese()==castOther.getPkAnamnese())
 && (this.getConsultaPkConsulta()==castOther.getConsultaPkConsulta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkAnamnese();
         result = 37 * result + this.getConsultaPkConsulta();
         return result;
   }   


}


