package MODELO;
// Generated 17/10/2016 13:02:11 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Consulta generated by hbm2java
 */
@Entity
@Table(name="consulta"
    ,catalog="BD_SIHV"
)
public class Consulta  implements java.io.Serializable {


     private int pkConsulta;
     private Adm adm;
     private Animais animais;
     private Date dataConsulta;
     private String sistemasAfetados;

    public Consulta() {
    }

	
    public Consulta(int pkConsulta, Adm adm, Animais animais, Date dataConsulta) {
        this.pkConsulta = pkConsulta;
        this.adm = adm;
        this.animais = animais;
        this.dataConsulta = dataConsulta;
    }
    public Consulta(int pkConsulta, Adm adm, Animais animais, Date dataConsulta, String sistemasAfetados) {
       this.pkConsulta = pkConsulta;
       this.adm = adm;
       this.animais = animais;
       this.dataConsulta = dataConsulta;
       this.sistemasAfetados = sistemasAfetados;
    }
   
     @Id 

    
    @Column(name="PK_consulta", unique=true, nullable=false)
    public int getPkConsulta() {
        return this.pkConsulta;
    }
    
    public void setPkConsulta(int pkConsulta) {
        this.pkConsulta = pkConsulta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="adm_PK_adm", referencedColumnName="PK_adm", nullable=false), 
        @JoinColumn(name="adm_FK_pessoa", referencedColumnName="FK_pessoa", nullable=false) } )
    public Adm getAdm() {
        return this.adm;
    }
    
    public void setAdm(Adm adm) {
        this.adm = adm;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="animais_PK_animal", referencedColumnName="PK_animal", nullable=false), 
        @JoinColumn(name="animais_cliente_FK_cliente", referencedColumnName="cliente_FK_cliente", nullable=false), 
        @JoinColumn(name="animais_cliente_FK_pessoa", referencedColumnName="cliente_FK_pessoa", nullable=false) } )
    public Animais getAnimais() {
        return this.animais;
    }
    
    public void setAnimais(Animais animais) {
        this.animais = animais;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DataConsulta", nullable=false, length=19)
    public Date getDataConsulta() {
        return this.dataConsulta;
    }
    
    public void setDataConsulta(Date dataConsulta) {
        this.dataConsulta = dataConsulta;
    }

    
    @Column(name="SistemasAfetados", length=500)
    public String getSistemasAfetados() {
        return this.sistemasAfetados;
    }
    
    public void setSistemasAfetados(String sistemasAfetados) {
        this.sistemasAfetados = sistemasAfetados;
    }




}


