package MODELO;
// Generated 21/10/2016 12:33:23 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ExameimageId generated by hbm2java
 */
@Embeddable
public class ExameimageId  implements java.io.Serializable {


     private int pkExameImage;
     private int consultaPkConsulta;

    public ExameimageId() {
    }

    public ExameimageId(int pkExameImage, int consultaPkConsulta) {
       this.pkExameImage = pkExameImage;
       this.consultaPkConsulta = consultaPkConsulta;
    }
   


    @Column(name="PK_ExameImage", nullable=false)
    public int getPkExameImage() {
        return this.pkExameImage;
    }
    
    public void setPkExameImage(int pkExameImage) {
        this.pkExameImage = pkExameImage;
    }


    @Column(name="consulta_PK_consulta", nullable=false)
    public int getConsultaPkConsulta() {
        return this.consultaPkConsulta;
    }
    
    public void setConsultaPkConsulta(int consultaPkConsulta) {
        this.consultaPkConsulta = consultaPkConsulta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ExameimageId) ) return false;
		 ExameimageId castOther = ( ExameimageId ) other; 
         
		 return (this.getPkExameImage()==castOther.getPkExameImage())
 && (this.getConsultaPkConsulta()==castOther.getConsultaPkConsulta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkExameImage();
         result = 37 * result + this.getConsultaPkConsulta();
         return result;
   }   


}


