package MODELO;
// Generated 21/10/2016 12:33:23 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Exameimage generated by hbm2java
 */
@Entity
@Table(name="exameimage"
    ,catalog="bd_sihv"
)
public class Exameimage  implements java.io.Serializable {


     private ExameimageId id;
     private Consulta consulta;
     private String regiExami;
     private String posicao;
     private Integer qtdChapas;
     private String laudo;
     private String tipo;
     private Date dataExaImage;

    public Exameimage() {
    }

	
    public Exameimage(ExameimageId id, Consulta consulta, String regiExami) {
        this.id = id;
        this.consulta = consulta;
        this.regiExami = regiExami;
    }
    public Exameimage(ExameimageId id, Consulta consulta, String regiExami, String posicao, Integer qtdChapas, String laudo, String tipo, Date dataExaImage) {
       this.id = id;
       this.consulta = consulta;
       this.regiExami = regiExami;
       this.posicao = posicao;
       this.qtdChapas = qtdChapas;
       this.laudo = laudo;
       this.tipo = tipo;
       this.dataExaImage = dataExaImage;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pkExameImage", column=@Column(name="PK_ExameImage", nullable=false) ), 
        @AttributeOverride(name="consultaPkConsulta", column=@Column(name="consulta_PK_consulta", nullable=false) ) } )
    public ExameimageId getId() {
        return this.id;
    }
    
    public void setId(ExameimageId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="consulta_PK_consulta", nullable=false, insertable=false, updatable=false)
    public Consulta getConsulta() {
        return this.consulta;
    }
    
    public void setConsulta(Consulta consulta) {
        this.consulta = consulta;
    }

    
    @Column(name="RegiExami", nullable=false, length=200)
    public String getRegiExami() {
        return this.regiExami;
    }
    
    public void setRegiExami(String regiExami) {
        this.regiExami = regiExami;
    }

    
    @Column(name="Posicao", length=50)
    public String getPosicao() {
        return this.posicao;
    }
    
    public void setPosicao(String posicao) {
        this.posicao = posicao;
    }

    
    @Column(name="QtdChapas")
    public Integer getQtdChapas() {
        return this.qtdChapas;
    }
    
    public void setQtdChapas(Integer qtdChapas) {
        this.qtdChapas = qtdChapas;
    }

    
    @Column(name="Laudo", length=200)
    public String getLaudo() {
        return this.laudo;
    }
    
    public void setLaudo(String laudo) {
        this.laudo = laudo;
    }

    
    @Column(name="Tipo", length=15)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DataExaImage", length=19)
    public Date getDataExaImage() {
        return this.dataExaImage;
    }
    
    public void setDataExaImage(Date dataExaImage) {
        this.dataExaImage = dataExaImage;
    }




}


