package MODELO;
// Generated 21/10/2016 12:33:23 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Examefisico generated by hbm2java
 */
@Entity
@Table(name="examefisico"
    ,catalog="bd_sihv"
)
public class Examefisico  implements java.io.Serializable {


     private ExamefisicoId id;
     private Consulta consulta;
     private double fcbpm;
     private double frmpm;
     private double termpeReta;
     private double tcp;
     private String estadoNutric;
     private String mucosaOral;
     private String mucosVagPeni;
     private String mucosaOcular;
     private String pulso;
     private String estadoPulso;
     private String hidratacao;
     private String palpaAbdom;
     private String auscuCardiaca;
     private String auscuPulmona;
     private String linfonodos;
     private String pelePelos;
     private int diagDiferenciais;

    public Examefisico() {
    }

    public Examefisico(ExamefisicoId id, Consulta consulta, double fcbpm, double frmpm, double termpeReta, double tcp, String estadoNutric, String mucosaOral, String mucosVagPeni, String mucosaOcular, String pulso, String estadoPulso, String hidratacao, String palpaAbdom, String auscuCardiaca, String auscuPulmona, String linfonodos, String pelePelos, int diagDiferenciais) {
       this.id = id;
       this.consulta = consulta;
       this.fcbpm = fcbpm;
       this.frmpm = frmpm;
       this.termpeReta = termpeReta;
       this.tcp = tcp;
       this.estadoNutric = estadoNutric;
       this.mucosaOral = mucosaOral;
       this.mucosVagPeni = mucosVagPeni;
       this.mucosaOcular = mucosaOcular;
       this.pulso = pulso;
       this.estadoPulso = estadoPulso;
       this.hidratacao = hidratacao;
       this.palpaAbdom = palpaAbdom;
       this.auscuCardiaca = auscuCardiaca;
       this.auscuPulmona = auscuPulmona;
       this.linfonodos = linfonodos;
       this.pelePelos = pelePelos;
       this.diagDiferenciais = diagDiferenciais;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pkExameFisico", column=@Column(name="PK_ExameFisico", nullable=false) ), 
        @AttributeOverride(name="consultaPkConsulta", column=@Column(name="consulta_PK_consulta", nullable=false) ) } )
    public ExamefisicoId getId() {
        return this.id;
    }
    
    public void setId(ExamefisicoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="consulta_PK_consulta", nullable=false, insertable=false, updatable=false)
    public Consulta getConsulta() {
        return this.consulta;
    }
    
    public void setConsulta(Consulta consulta) {
        this.consulta = consulta;
    }

    
    @Column(name="FCbpm", nullable=false, precision=22, scale=0)
    public double getFcbpm() {
        return this.fcbpm;
    }
    
    public void setFcbpm(double fcbpm) {
        this.fcbpm = fcbpm;
    }

    
    @Column(name="FRmpm", nullable=false, precision=22, scale=0)
    public double getFrmpm() {
        return this.frmpm;
    }
    
    public void setFrmpm(double frmpm) {
        this.frmpm = frmpm;
    }

    
    @Column(name="TermpeReta", nullable=false, precision=22, scale=0)
    public double getTermpeReta() {
        return this.termpeReta;
    }
    
    public void setTermpeReta(double termpeReta) {
        this.termpeReta = termpeReta;
    }

    
    @Column(name="TCP", nullable=false, precision=22, scale=0)
    public double getTcp() {
        return this.tcp;
    }
    
    public void setTcp(double tcp) {
        this.tcp = tcp;
    }

    
    @Column(name="EstadoNutric", nullable=false, length=9)
    public String getEstadoNutric() {
        return this.estadoNutric;
    }
    
    public void setEstadoNutric(String estadoNutric) {
        this.estadoNutric = estadoNutric;
    }

    
    @Column(name="MucosaOral", nullable=false, length=10)
    public String getMucosaOral() {
        return this.mucosaOral;
    }
    
    public void setMucosaOral(String mucosaOral) {
        this.mucosaOral = mucosaOral;
    }

    
    @Column(name="MucosVagPeni", nullable=false, length=10)
    public String getMucosVagPeni() {
        return this.mucosVagPeni;
    }
    
    public void setMucosVagPeni(String mucosVagPeni) {
        this.mucosVagPeni = mucosVagPeni;
    }

    
    @Column(name="MucosaOcular", nullable=false, length=10)
    public String getMucosaOcular() {
        return this.mucosaOcular;
    }
    
    public void setMucosaOcular(String mucosaOcular) {
        this.mucosaOcular = mucosaOcular;
    }

    
    @Column(name="Pulso", nullable=false, length=7)
    public String getPulso() {
        return this.pulso;
    }
    
    public void setPulso(String pulso) {
        this.pulso = pulso;
    }

    
    @Column(name="EstadoPulso", nullable=false, length=9)
    public String getEstadoPulso() {
        return this.estadoPulso;
    }
    
    public void setEstadoPulso(String estadoPulso) {
        this.estadoPulso = estadoPulso;
    }

    
    @Column(name="Hidratacao", nullable=false, length=22)
    public String getHidratacao() {
        return this.hidratacao;
    }
    
    public void setHidratacao(String hidratacao) {
        this.hidratacao = hidratacao;
    }

    
    @Column(name="PalpaAbdom", nullable=false, length=200)
    public String getPalpaAbdom() {
        return this.palpaAbdom;
    }
    
    public void setPalpaAbdom(String palpaAbdom) {
        this.palpaAbdom = palpaAbdom;
    }

    
    @Column(name="AuscuCardiaca", nullable=false, length=200)
    public String getAuscuCardiaca() {
        return this.auscuCardiaca;
    }
    
    public void setAuscuCardiaca(String auscuCardiaca) {
        this.auscuCardiaca = auscuCardiaca;
    }

    
    @Column(name="AuscuPulmona", nullable=false, length=200)
    public String getAuscuPulmona() {
        return this.auscuPulmona;
    }
    
    public void setAuscuPulmona(String auscuPulmona) {
        this.auscuPulmona = auscuPulmona;
    }

    
    @Column(name="Linfonodos", nullable=false, length=200)
    public String getLinfonodos() {
        return this.linfonodos;
    }
    
    public void setLinfonodos(String linfonodos) {
        this.linfonodos = linfonodos;
    }

    
    @Column(name="PelePelos", nullable=false, length=200)
    public String getPelePelos() {
        return this.pelePelos;
    }
    
    public void setPelePelos(String pelePelos) {
        this.pelePelos = pelePelos;
    }

    
    @Column(name="DiagDiferenciais", nullable=false)
    public int getDiagDiferenciais() {
        return this.diagDiferenciais;
    }
    
    public void setDiagDiferenciais(int diagDiferenciais) {
        this.diagDiferenciais = diagDiferenciais;
    }




}


