package MODELO;
// Generated 31/07/2016 22:50:27 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pessoa generated by hbm2java
 */
@Entity
@Table(name="pessoa"
    ,catalog="BD_SIHV"
)
public class Pessoa  implements java.io.Serializable {


     private Integer pkPessoa;
     private long cpf;
     private int rg;
     private String nome;
     private String sexo;
     private String logra;
     private String casaNumero;
     private String bairro;
     private String cidade;
     private int cep;
     private String complemento;
     private String uf;
     private Boolean exclusaoLogica;
     private Date cadDataHora;
     private Set<Cliente> clientes = new HashSet<Cliente>(0);
     private Set<Telefone> telefones = new HashSet<Telefone>(0);
     private Set<Adm> adms = new HashSet<Adm>(0);

    public Pessoa() {
    }

	
    public Pessoa(long cpf, int rg, String nome, String sexo, String logra, String casaNumero, String bairro, String cidade, int cep, String uf, Date cadDataHora) {
        this.cpf = cpf;
        this.rg = rg;
        this.nome = nome;
        this.sexo = sexo;
        this.logra = logra;
        this.casaNumero = casaNumero;
        this.bairro = bairro;
        this.cidade = cidade;
        this.cep = cep;
        this.uf = uf;
        this.cadDataHora = cadDataHora;
    }
    public Pessoa(long cpf, int rg, String nome, String sexo, String logra, String casaNumero, String bairro, String cidade, int cep, String complemento, String uf, Boolean exclusaoLogica, Date cadDataHora, Set<Cliente> clientes, Set<Telefone> telefones, Set<Adm> adms) {
       this.cpf = cpf;
       this.rg = rg;
       this.nome = nome;
       this.sexo = sexo;
       this.logra = logra;
       this.casaNumero = casaNumero;
       this.bairro = bairro;
       this.cidade = cidade;
       this.cep = cep;
       this.complemento = complemento;
       this.uf = uf;
       this.exclusaoLogica = exclusaoLogica;
       this.cadDataHora = cadDataHora;
       this.clientes = clientes;
       this.telefones = telefones;
       this.adms = adms;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_pessoa", unique=true, nullable=false)
    public Integer getPkPessoa() {
        return this.pkPessoa;
    }
    
    public void setPkPessoa(Integer pkPessoa) {
        this.pkPessoa = pkPessoa;
    }

    
    @Column(name="CPF", nullable=false)
    public long getCpf() {
        return this.cpf;
    }
    
    public void setCpf(long cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="RG", nullable=false)
    public int getRg() {
        return this.rg;
    }
    
    public void setRg(int rg) {
        this.rg = rg;
    }

    
    @Column(name="NOME", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="SEXO", nullable=false, length=3)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    
    @Column(name="LOGRA", nullable=false, length=100)
    public String getLogra() {
        return this.logra;
    }
    
    public void setLogra(String logra) {
        this.logra = logra;
    }

    
    @Column(name="CASA_NUMERO", nullable=false, length=7)
    public String getCasaNumero() {
        return this.casaNumero;
    }
    
    public void setCasaNumero(String casaNumero) {
        this.casaNumero = casaNumero;
    }

    
    @Column(name="BAIRRO", nullable=false, length=100)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="CIDADE", nullable=false, length=100)
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="CEP", nullable=false)
    public int getCep() {
        return this.cep;
    }
    
    public void setCep(int cep) {
        this.cep = cep;
    }

    
    @Column(name="COMPLEMENTO", length=100)
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }

    
    @Column(name="UF", nullable=false, length=80)
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }

    
    @Column(name="exclusaoLogica")
    public Boolean getExclusaoLogica() {
        return this.exclusaoLogica;
    }
    
    public void setExclusaoLogica(Boolean exclusaoLogica) {
        this.exclusaoLogica = exclusaoLogica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CAD_DATA_HORA", nullable=false, length=19)
    public Date getCadDataHora() {
        return this.cadDataHora;
    }
    
    public void setCadDataHora(Date cadDataHora) {
        this.cadDataHora = cadDataHora;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pessoa")
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pessoa")
    public Set<Telefone> getTelefones() {
        return this.telefones;
    }
    
    public void setTelefones(Set<Telefone> telefones) {
        this.telefones = telefones;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pessoa")
    public Set<Adm> getAdms() {
        return this.adms;
    }
    
    public void setAdms(Set<Adm> adms) {
        this.adms = adms;
    }




}


